[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = '2021'
name = 'pallet-evm-precompile-parachain-staking'
version = '0.1.0'

[dependencies]
pallet-parachain-staking = { workspace = true }
precompile-utils = { workspace = true }

frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true, features = ["disable_panic_handler"] }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

fp-evm = { workspace = true }
pallet-evm = { workspace = true }

[dev-dependencies]
derive_more = { workspace = true }
scale-info = { workspace = true }
serde = { workspace = true }
sha3 = { workspace = true }
precompile-utils = { workspace = true, features = ["std", "testing"] }
pallet-balances = { workspace = true, features = ["std", "insecure_zero_ed"] }
pallet-timestamp = { workspace = true, features = ["std"] }
parity-scale-codec = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
    "fp-evm/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-evm/std",
    "pallet-parachain-staking/std",
    "precompile-utils/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
]
