[package]
name = "intent-token-query"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
alloy = { workspace = true, features = ["contract", "signer-local", "rpc", "rpc-types", "eips"] }
oe-client-ethereum = { workspace = true }
oe-client-solana = { workspace = true }
serde_json = { workspace = true }
solana-account-decoder-client-types = "2.1.5"
solana-client = { workspace = true }
solana-sdk = { workspace = true }
spl-token = { workspace = true }
tracing = { workspace = true }

executor-primitives = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
hex-literal = { workspace = true }
mockall = { workspace = true }
oe-client-ethereum = { workspace = true, features = ["mocks"] }
oe-client-solana = { workspace = true, features = ["mocks"] }
base64 = { workspace = true }

[lints]
workspace = true
