[package]
name = "bc-musig2-ceremony"
authors = ["Trust Computing GmbH <info@litentry.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
musig2 = { workspace = true, optional = true }
rand = { version = "0.8.5", optional = true }

# sgx dependencies
musig2_sgx = { workspace = true, optional = true }
sgx_rand = { workspace = true, optional = true }
sgx_tstd = { workspace = true, features = ["net", "thread"], optional = true }

codec = { package = "parity-scale-codec", workspace = true }
k256 = { workspace = true, features = ["ecdsa-core", "schnorr", "alloc"] }
log = { workspace = true }

itp-sgx-crypto = { workspace = true }
litentry-primitives = { workspace = true }

[dev-dependencies]
rand = { version = "0.8.5" }
signature = "2.1.0"

[features]
default = ["std"]
sgx-test = ["sgx"]
std = [
    "musig2",
    "log/std",
    "litentry-primitives/std",
    "itp-sgx-crypto/std",
    "rand",
]
sgx = [
    "sgx_tstd",
    "musig2_sgx",
    "litentry-primitives/sgx",
    "itp-sgx-crypto/sgx",
    "sgx_rand",
]
