[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
accounting_contract = "EJgprV3h3RECRWtsMnee6FUD8CT5AUk3nMFXb7PA4xYP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "test-account.json"

[scripts]
test = "cargo test"
