[package]
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = '2021'
homepage = 'https://litentry.com'
name = 'pallet-identity-management-tee'
repository = 'https://github.com/litentry/heima'
version = '0.1.0'

[dependencies]
codec = { package = "parity-scale-codec", workspace = true, features = ["max-encoded-len"] }
hex = { workspace = true }
log = { workspace = true }
scale-info = { workspace = true }

frame-support = { workspace = true }
frame-system = { workspace = true }
litentry-primitives = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
pallet-balances = { workspace = true }

[features]
default = ["std"]

std = [
    "codec/std",
    "sp-std/std",
    "sp-runtime/std",
    "sp-io/std",
    "sp-core/std",
    "frame-support/std",
    "frame-system/std",
    "log/std",
    "pallet-balances/std",
    "litentry-primitives/std",
]

development = []
