[package]
name = "tests"
version = "0.1.0"
description = "Created with Anchor"
edition.workspace = true

[dependencies]
accounting-contract = { path = "../programs/accounting-contract" }
anchor-client = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
