[package]
name = "lc-teebag-storage"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition = "2021"

[dependencies]
itp-storage = { path = "../../../core-primitives/storage", default-features = false }
itp-types = { path = "../../../core-primitives/types", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42", default-features = false }

[features]
default = ["std"]
std = [
    "sp-std/std",
    "itp-storage/std",
    "itp-types/std",
]
