[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-identity-verification"
version = "0.1.0"

[dependencies]
# std dependencies
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
hex = { version = "0.4.3", default-features = false }
http = { version = "0.2", optional = true }
http_req = { optional = true, features = ["rust-tls"], branch = "master", git = "https://github.com/integritee-network/http_req" }
lru = "0.12.3"
rand = { version = "0.8", optional = true }

# sgx dependencies
futures_sgx = { package = "futures", git = "https://github.com/mesalock-linux/futures-rs-sgx", optional = true }
http-sgx = { package = "http", git = "https://github.com/integritee-network/http-sgx.git", branch = "sgx-experimental", optional = true }
http_req-sgx = { package = "http_req", git = "https://github.com/integritee-network/http_req", default-features = false, features = ["rust-tls", "sgx"], optional = true }
sgx_rand = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "master", features = ["net", "thread"], optional = true }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# no_std dependencies
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
log = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
url = { git = "https://github.com/domenukk/rust-url", branch = "no_std", default-features = false, features = ["alloc", "no_std_net"] }

# internal dependencies
itc-rest-client = { path = "../../../core/rest-client", default-features = false }
itp-sgx-crypto = { path = "../../../core-primitives/sgx/crypto", default-features = false }
itp-utils = { path = "../../../core-primitives/utils", default-features = false }

codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

lc-data-providers = { path = "../data-providers", default-features = false }
lc-stf-task-sender = { path = "../stf-task/sender", default-features = false }
litentry-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
sgx = [
    "futures_sgx",
    "http-sgx",
    "http_req-sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "sgx_rand",
    "itp-sgx-crypto/sgx",
    "lc-data-providers/sgx",
    "litentry-primitives/sgx",
    "lc-stf-task-sender/sgx",
]
std = [
    "http",
    "http_req",
    "log/std",
    "serde/std",
    "serde_json/std",
    "url/std",
    "itp-sgx-crypto/std",
    "frame-support/std",
    "lc-data-providers/std",
    "litentry-primitives/std",
    "lc-stf-task-sender/std",
    "rand",
]
