[package]
name = "itp-networking-utils"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
sgx_tstd = { workspace = true, optional = true }

[features]
default = ["std"]
std = []
sgx = [
    "sgx_tstd",
]
