// Copyright 2020-2024 Trust Computing GmbH.
// This file is part of Litentry.
//
// Litentry is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Litentry is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Litentry.  If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_teebag`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2025-03-04, STEPS: `20`, REPEAT: `50`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `stress-test-server`, CPU: `AMD EPYC 7B12`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("litentry-dev")`, DB CACHE: 20

// Executed Command:
// ./litentry-collator
// benchmark
// pallet
// --chain=litentry-dev
// --execution=wasm
// --db-cache=20
// --wasm-execution=compiled
// --pallet=pallet_teebag
// --extrinsic=*
// --heap-pages=4096
// --steps=20
// --repeat=50
// --header=./LICENSE_HEADER
// --output=./runtime/litentry/src/weights/pallet_teebag.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_teebag`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_teebag::WeightInfo for WeightInfo<T> {
	/// Storage: `Teebag::EnclaveRegistry` (r:1 w:1)
	/// Proof: `Teebag::EnclaveRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::Mode` (r:1 w:0)
	/// Proof: `Teebag::Mode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::EnclaveIdentifier` (r:1 w:1)
	/// Proof: `Teebag::EnclaveIdentifier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_add_enclave() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `190`
		//  Estimated: `3655`
		// Minimum execution time: 15_820_000 picoseconds.
		Weight::from_parts(16_521_000, 0)
			.saturating_add(Weight::from_parts(0, 3655))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Teebag::EnclaveRegistry` (r:1 w:1)
	/// Proof: `Teebag::EnclaveRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::EnclaveIdentifier` (r:1 w:1)
	/// Proof: `Teebag::EnclaveIdentifier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_remove_enclave() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `508`
		//  Estimated: `3973`
		// Minimum execution time: 15_740_000 picoseconds.
		Weight::from_parts(16_700_000, 0)
			.saturating_add(Weight::from_parts(0, 3973))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Teebag::EnclaveRegistry` (r:4 w:3)
	/// Proof: `Teebag::EnclaveRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::EnclaveIdentifier` (r:1 w:1)
	/// Proof: `Teebag::EnclaveIdentifier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_remove_enclave_by_mrenclave() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `687`
		//  Estimated: `11577`
		// Minimum execution time: 40_851_000 picoseconds.
		Weight::from_parts(42_020_000, 0)
			.saturating_add(Weight::from_parts(0, 11577))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Teebag::EnclaveRegistry` (r:4 w:3)
	/// Proof: `Teebag::EnclaveRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::EnclaveIdentifier` (r:1 w:1)
	/// Proof: `Teebag::EnclaveIdentifier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_remove_enclave_by_worker_type() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `687`
		//  Estimated: `11577`
		// Minimum execution time: 40_001_000 picoseconds.
		Weight::from_parts(41_440_000, 0)
			.saturating_add(Weight::from_parts(0, 11577))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Teebag::AuthorizedEnclave` (r:1 w:1)
	/// Proof: `Teebag::AuthorizedEnclave` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_add_authorized_enclave() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `350`
		//  Estimated: `3815`
		// Minimum execution time: 9_970_000 picoseconds.
		Weight::from_parts(10_550_000, 0)
			.saturating_add(Weight::from_parts(0, 3815))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Teebag::AuthorizedEnclave` (r:1 w:1)
	/// Proof: `Teebag::AuthorizedEnclave` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::EnclaveRegistry` (r:1 w:0)
	/// Proof: `Teebag::EnclaveRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_remove_authorized_enclave() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `3847`
		// Minimum execution time: 14_640_000 picoseconds.
		Weight::from_parts(15_540_000, 0)
			.saturating_add(Weight::from_parts(0, 3847))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Teebag::Mode` (r:1 w:0)
	/// Proof: `Teebag::Mode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::AuthorizedEnclave` (r:1 w:1)
	/// Proof: `Teebag::AuthorizedEnclave` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::EnclaveRegistry` (r:1 w:1)
	/// Proof: `Teebag::EnclaveRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::EnclaveIdentifier` (r:1 w:1)
	/// Proof: `Teebag::EnclaveIdentifier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_enclave_with_ias_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `357`
		//  Estimated: `3822`
		// Minimum execution time: 1_676_850_000 picoseconds.
		Weight::from_parts(1_699_789_000, 0)
			.saturating_add(Weight::from_parts(0, 3822))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Teebag::QuotingEnclaveRegistry` (r:1 w:0)
	/// Proof: `Teebag::QuotingEnclaveRegistry` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::TcbInfo` (r:1 w:0)
	/// Proof: `Teebag::TcbInfo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::Mode` (r:1 w:0)
	/// Proof: `Teebag::Mode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::AuthorizedEnclave` (r:1 w:1)
	/// Proof: `Teebag::AuthorizedEnclave` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::EnclaveRegistry` (r:1 w:1)
	/// Proof: `Teebag::EnclaveRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::EnclaveIdentifier` (r:1 w:1)
	/// Proof: `Teebag::EnclaveIdentifier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_enclave_with_dcap_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `574`
		//  Estimated: `4039`
		// Minimum execution time: 3_332_320_000 picoseconds.
		Weight::from_parts(3_385_050_000, 0)
			.saturating_add(Weight::from_parts(0, 4039))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Teebag::EnclaveRegistry` (r:1 w:1)
	/// Proof: `Teebag::EnclaveRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::EnclaveIdentifier` (r:1 w:1)
	/// Proof: `Teebag::EnclaveIdentifier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn unregister_enclave() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `425`
		//  Estimated: `3890`
		// Minimum execution time: 17_269_000 picoseconds.
		Weight::from_parts(18_690_000, 0)
			.saturating_add(Weight::from_parts(0, 3890))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Teebag::QuotingEnclaveRegistry` (r:0 w:1)
	/// Proof: `Teebag::QuotingEnclaveRegistry` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn register_quoting_enclave() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `94`
		//  Estimated: `1493`
		// Minimum execution time: 1_655_980_000 picoseconds.
		Weight::from_parts(1_680_810_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Teebag::TcbInfo` (r:0 w:1)
	/// Proof: `Teebag::TcbInfo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_tcb_info() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `94`
		//  Estimated: `1493`
		// Minimum execution time: 1_810_750_000 picoseconds.
		Weight::from_parts(1_831_120_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn post_opaque_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_420_000 picoseconds.
		Weight::from_parts(4_730_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// Storage: `Teebag::EnclaveRegistry` (r:1 w:0)
	/// Proof: `Teebag::EnclaveRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn parentchain_block_processed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `374`
		//  Estimated: `3839`
		// Minimum execution time: 12_590_000 picoseconds.
		Weight::from_parts(13_500_000, 0)
			.saturating_add(Weight::from_parts(0, 3839))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `Teebag::EnclaveRegistry` (r:1 w:0)
	/// Proof: `Teebag::EnclaveRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Teebag::EnclaveIdentifier` (r:1 w:0)
	/// Proof: `Teebag::EnclaveIdentifier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::SidechainBlockFinalizationCandidate` (r:1 w:1)
	/// Proof: `Teebag::SidechainBlockFinalizationCandidate` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teebag::LatestSidechainBlockConfirmation` (r:0 w:1)
	/// Proof: `Teebag::LatestSidechainBlockConfirmation` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sidechain_block_imported() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `495`
		//  Estimated: `3960`
		// Minimum execution time: 21_650_000 picoseconds.
		Weight::from_parts(22_560_000, 0)
			.saturating_add(Weight::from_parts(0, 3960))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Teebag::EnclaveIdentifier` (r:1 w:1)
	/// Proof: `Teebag::EnclaveIdentifier` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_enclave_identifier() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `3645`
		// Minimum execution time: 5_960_000 picoseconds.
		Weight::from_parts(6_220_000, 0)
			.saturating_add(Weight::from_parts(0, 3645))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
