// Copyright 2020-2024 Trust Computing GmbH.
// This file is part of Litentry.
//
// Litentry is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Litentry is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Litentry.  If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_identity`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2025-03-04, STEPS: `20`, REPEAT: `50`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `stress-test-server`, CPU: `AMD EPYC 7B12`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("litentry-dev")`, DB CACHE: 20

// Executed Command:
// ./litentry-collator
// benchmark
// pallet
// --chain=litentry-dev
// --execution=wasm
// --db-cache=20
// --wasm-execution=compiled
// --pallet=pallet_identity
// --extrinsic=*
// --heap-pages=4096
// --steps=20
// --repeat=50
// --header=./LICENSE_HEADER
// --output=./runtime/litentry/src/weights/pallet_identity.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_identity`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_identity::WeightInfo for WeightInfo<T> {
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn add_registrar(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `70 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 8_680_000 picoseconds.
		Weight::from_parts(9_596_249, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 2_164
			.saturating_add(Weight::from_parts(89_263, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	fn set_identity(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7016 + r * (5 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 109_130_000 picoseconds.
		Weight::from_parts(110_968_152, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 23_168
			.saturating_add(Weight::from_parts(523_215, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:100 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 100]`.
	fn set_subs_new(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `11037 + s * (2589 ±0)`
		// Minimum execution time: 9_670_000 picoseconds.
		Weight::from_parts(20_129_304, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 6_117
			.saturating_add(Weight::from_parts(3_333_147, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
			.saturating_add(Weight::from_parts(0, 2589).saturating_mul(s.into()))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:0 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[0, 100]`.
	fn set_subs_old(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231 + p * (32 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 9_980_000 picoseconds.
		Weight::from_parts(20_690_998, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 4_770
			.saturating_add(Weight::from_parts(1_377_149, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
	}
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:0 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	/// The range of component `s` is `[0, 100]`.
	fn clear_identity(r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7108 + r * (5 ±0) + s * (32 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 57_230_000 picoseconds.
		Weight::from_parts(51_818_346, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 32_350
			.saturating_add(Weight::from_parts(573_317, 0).saturating_mul(r.into()))
			// Standard Error: 6_118
			.saturating_add(Weight::from_parts(1_428_655, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:0)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	fn request_judgement(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7006 + r * (57 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 76_640_000 picoseconds.
		Weight::from_parts(78_960_408, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 13_208
			.saturating_add(Weight::from_parts(90_152, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	fn cancel_request(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7037`
		//  Estimated: `11037`
		// Minimum execution time: 75_110_000 picoseconds.
		Weight::from_parts(77_590_661, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 16_774
			.saturating_add(Weight::from_parts(15_622, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn set_fee(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `127 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 6_560_000 picoseconds.
		Weight::from_parts(7_211_815, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 1_595
			.saturating_add(Weight::from_parts(75_122, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn set_account_id(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `127 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 6_531_000 picoseconds.
		Weight::from_parts(7_085_278, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 1_490
			.saturating_add(Weight::from_parts(83_218, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn set_fields(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `127 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 6_540_000 picoseconds.
		Weight::from_parts(7_180_590, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 1_582
			.saturating_add(Weight::from_parts(68_171, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:0)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn provide_judgement(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7084 + r * (57 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 97_210_000 picoseconds.
		Weight::from_parts(99_489_564, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 16_403
			.saturating_add(Weight::from_parts(115_688, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:0 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	/// The range of component `s` is `[0, 100]`.
	fn kill_identity(r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7368 + r * (15 ±0) + s * (32 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 70_821_000 picoseconds.
		Weight::from_parts(72_499_165, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 35_809
			.saturating_add(Weight::from_parts(478_500, 0).saturating_mul(r.into()))
			// Standard Error: 6_773
			.saturating_add(Weight::from_parts(1_438_069, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 99]`.
	fn add_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493 + s * (36 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 25_900_000 picoseconds.
		Weight::from_parts(30_835_041, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 1_815
			.saturating_add(Weight::from_parts(83_080, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 100]`.
	fn rename_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `618 + s * (3 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 13_870_000 picoseconds.
		Weight::from_parts(16_322_801, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 882
			.saturating_add(Weight::from_parts(27_497, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 100]`.
	fn remove_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `661 + s * (35 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 30_230_000 picoseconds.
		Weight::from_parts(33_618_974, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 1_257
			.saturating_add(Weight::from_parts(62_204, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 99]`.
	fn quit_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `690 + s * (37 ±0)`
		//  Estimated: `6723`
		// Minimum execution time: 22_461_000 picoseconds.
		Weight::from_parts(24_712_978, 0)
			.saturating_add(Weight::from_parts(0, 6723))
			// Standard Error: 1_026
			.saturating_add(Weight::from_parts(67_188, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ParachainIdentity::UsernameAuthorities` (r:0 w:1)
	/// Proof: `ParachainIdentity::UsernameAuthorities` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn add_username_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_871_000 picoseconds.
		Weight::from_parts(6_340_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::UsernameAuthorities` (r:1 w:1)
	/// Proof: `ParachainIdentity::UsernameAuthorities` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn remove_username_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `118`
		//  Estimated: `3517`
		// Minimum execution time: 9_560_000 picoseconds.
		Weight::from_parts(10_140_000, 0)
			.saturating_add(Weight::from_parts(0, 3517))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::UsernameAuthorities` (r:1 w:1)
	/// Proof: `ParachainIdentity::UsernameAuthorities` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:1 w:1)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::PendingUsernames` (r:1 w:0)
	/// Proof: `ParachainIdentity::PendingUsernames` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	fn set_username_for() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `118`
		//  Estimated: `11037`
		// Minimum execution time: 70_771_000 picoseconds.
		Weight::from_parts(75_210_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `ParachainIdentity::PendingUsernames` (r:1 w:1)
	/// Proof: `ParachainIdentity::PendingUsernames` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:0 w:1)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	fn accept_username() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `11037`
		// Minimum execution time: 20_819_000 picoseconds.
		Weight::from_parts(21_740_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `ParachainIdentity::PendingUsernames` (r:1 w:1)
	/// Proof: `ParachainIdentity::PendingUsernames` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn remove_expired_approval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `3550`
		// Minimum execution time: 30_210_000 picoseconds.
		Weight::from_parts(34_281_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:1 w:0)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	fn set_primary_username() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `295`
		//  Estimated: `11037`
		// Minimum execution time: 16_930_000 picoseconds.
		Weight::from_parts(17_750_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:1 w:1)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	fn remove_dangling_username() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `136`
		//  Estimated: `11037`
		// Minimum execution time: 12_060_000 picoseconds.
		Weight::from_parts(12_520_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
