// Copyright 2020-2024 Trust Computing GmbH.
// This file is part of Litentry.
//
// Litentry is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Litentry is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Litentry.  If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_identity`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2025-03-04, STEPS: `20`, REPEAT: `50`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `parachain-dev-1`, CPU: `AMD EPYC 7B12`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("litentry-dev")`, DB CACHE: 20

// Executed Command:
// ./target/production/litentry-collator
// benchmark
// pallet
// --chain=litentry-dev
// --execution=wasm
// --db-cache=20
// --wasm-execution=compiled
// --pallet=pallet_identity
// --extrinsic=*
// --heap-pages=4096
// --steps=20
// --repeat=50
// --header=./LICENSE_HEADER
// --output=./runtime/litentry/src/weights/pallet_identity.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_identity`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_identity::WeightInfo for WeightInfo<T> {
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn add_registrar(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `70 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 8_470_000 picoseconds.
		Weight::from_parts(9_277_763, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 2_300
			.saturating_add(Weight::from_parts(94_750, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	fn set_identity(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7016 + r * (5 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 112_120_000 picoseconds.
		Weight::from_parts(114_633_016, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 21_234
			.saturating_add(Weight::from_parts(202_031, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:100 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 100]`.
	fn set_subs_new(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `11037 + s * (2589 ±0)`
		// Minimum execution time: 9_860_000 picoseconds.
		Weight::from_parts(20_142_934, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 5_935
			.saturating_add(Weight::from_parts(3_371_245, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
			.saturating_add(Weight::from_parts(0, 2589).saturating_mul(s.into()))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:0 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[0, 100]`.
	fn set_subs_old(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231 + p * (32 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 9_890_000 picoseconds.
		Weight::from_parts(20_030_874, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 4_966
			.saturating_add(Weight::from_parts(1_448_577, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
	}
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:0 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	/// The range of component `s` is `[0, 100]`.
	fn clear_identity(r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7108 + r * (5 ±0) + s * (32 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 54_550_000 picoseconds.
		Weight::from_parts(49_321_120, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 24_909
			.saturating_add(Weight::from_parts(378_091, 0).saturating_mul(r.into()))
			// Standard Error: 4_711
			.saturating_add(Weight::from_parts(1_459_575, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:0)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	fn request_judgement(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7006 + r * (57 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 76_790_000 picoseconds.
		Weight::from_parts(78_831_502, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 10_455
			.saturating_add(Weight::from_parts(113_634, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	fn cancel_request(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7037`
		//  Estimated: `11037`
		// Minimum execution time: 77_460_000 picoseconds.
		Weight::from_parts(79_058_450, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 9_352
			.saturating_add(Weight::from_parts(100_290, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn set_fee(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `127 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 6_470_000 picoseconds.
		Weight::from_parts(6_929_173, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 1_398
			.saturating_add(Weight::from_parts(72_276, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn set_account_id(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `127 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 6_440_000 picoseconds.
		Weight::from_parts(6_895_507, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 1_322
			.saturating_add(Weight::from_parts(71_766, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn set_fields(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `127 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 6_250_000 picoseconds.
		Weight::from_parts(6_758_597, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 1_326
			.saturating_add(Weight::from_parts(72_412, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:0)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn provide_judgement(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7084 + r * (57 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 101_080_000 picoseconds.
		Weight::from_parts(102_664_298, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 27_745
			.saturating_add(Weight::from_parts(303_001, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:0 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	/// The range of component `s` is `[0, 100]`.
	fn kill_identity(r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7368 + r * (15 ±0) + s * (32 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 70_960_000 picoseconds.
		Weight::from_parts(67_493_846, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 34_227
			.saturating_add(Weight::from_parts(380_349, 0).saturating_mul(r.into()))
			// Standard Error: 6_473
			.saturating_add(Weight::from_parts(1_454_115, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 99]`.
	fn add_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493 + s * (36 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 26_280_000 picoseconds.
		Weight::from_parts(31_301_452, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 1_738
			.saturating_add(Weight::from_parts(75_994, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 100]`.
	fn rename_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `618 + s * (3 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 13_640_000 picoseconds.
		Weight::from_parts(15_906_112, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 776
			.saturating_add(Weight::from_parts(29_394, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 100]`.
	fn remove_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `661 + s * (35 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 30_570_000 picoseconds.
		Weight::from_parts(33_684_152, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 1_124
			.saturating_add(Weight::from_parts(62_550, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 99]`.
	fn quit_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `690 + s * (37 ±0)`
		//  Estimated: `6723`
		// Minimum execution time: 22_130_000 picoseconds.
		Weight::from_parts(24_741_796, 0)
			.saturating_add(Weight::from_parts(0, 6723))
			// Standard Error: 1_155
			.saturating_add(Weight::from_parts(63_901, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ParachainIdentity::UsernameAuthorities` (r:0 w:1)
	/// Proof: `ParachainIdentity::UsernameAuthorities` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn add_username_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_960_000 picoseconds.
		Weight::from_parts(6_449_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::UsernameAuthorities` (r:1 w:1)
	/// Proof: `ParachainIdentity::UsernameAuthorities` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn remove_username_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `118`
		//  Estimated: `3517`
		// Minimum execution time: 9_470_000 picoseconds.
		Weight::from_parts(9_870_000, 0)
			.saturating_add(Weight::from_parts(0, 3517))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::UsernameAuthorities` (r:1 w:1)
	/// Proof: `ParachainIdentity::UsernameAuthorities` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:1 w:1)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::PendingUsernames` (r:1 w:0)
	/// Proof: `ParachainIdentity::PendingUsernames` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	fn set_username_for() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `118`
		//  Estimated: `11037`
		// Minimum execution time: 69_550_000 picoseconds.
		Weight::from_parts(72_651_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `ParachainIdentity::PendingUsernames` (r:1 w:1)
	/// Proof: `ParachainIdentity::PendingUsernames` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:0 w:1)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	fn accept_username() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `11037`
		// Minimum execution time: 20_780_000 picoseconds.
		Weight::from_parts(21_760_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `ParachainIdentity::PendingUsernames` (r:1 w:1)
	/// Proof: `ParachainIdentity::PendingUsernames` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn remove_expired_approval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `3550`
		// Minimum execution time: 24_929_000 picoseconds.
		Weight::from_parts(36_120_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:1 w:0)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	fn set_primary_username() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `295`
		//  Estimated: `11037`
		// Minimum execution time: 16_680_000 picoseconds.
		Weight::from_parts(17_431_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:1 w:1)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	fn remove_dangling_username() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `136`
		//  Estimated: `11037`
		// Minimum execution time: 11_730_000 picoseconds.
		Weight::from_parts(12_210_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
