[package]
name = "ita-stf"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# crates.io
codec = { version = "3.0.0", default-features = false, features = ["derive"], package = "parity-scale-codec" }
hex = { version = "0.4", default-features = false }
hex-literal = { version = "0.4" }
log = { version = "0.4", default-features = false }
rlp = { version = "0.5", default-features = false }
sha3 = { version = "0.10", default-features = false }

# sgx deps
sgx_tstd = { branch = "master", features = ["untrusted_fs", "net", "backtrace"], git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# local crates
ita-sgx-runtime = { default-features = false, path = "../sgx-runtime" }
itp-hashing = { default-features = false, path = "../../core-primitives/hashing" }
itp-node-api = { default-features = false, path = "../../core-primitives/node-api" }
itp-node-api-metadata = { default-features = false, path = "../../core-primitives/node-api/metadata" }
itp-sgx-externalities = { default-features = false, path = "../../core-primitives/substrate-sgx/externalities" }
itp-sgx-runtime-primitives = { default-features = false, path = "../../core-primitives/sgx-runtime-primitives" }
itp-stf-interface = { default-features = false, path = "../../core-primitives/stf-interface" }
itp-stf-primitives = { default-features = false, path = "../../core-primitives/stf-primitives" }
itp-storage = { default-features = false, path = "../../core-primitives/storage" }
itp-types = { default-features = false, path = "../../core-primitives/types" }
itp-utils = { default-features = false, path = "../../core-primitives/utils" }
sp-io = { default-features = false, features = ["disable_oom", "disable_panic_handler", "disable_allocator"], path = "../../core-primitives/substrate-sgx/sp-io" }

# Substrate dependencies
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-sudo = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# litentry
itp-node-api-metadata-provider = { path = "../../core-primitives/node-api/metadata-provider", default-features = false }
lc-stf-task-sender = { path = "../../litentry/core/stf-task/sender", default-features = false }
litentry-hex-utils = { path = "../../../primitives/hex", default-features = false }
litentry-macros = { path = "../../../primitives/core/macros", default-features = false }
litentry-primitives = { path = "../../litentry/primitives", default-features = false }
pallet-parentchain = { path = "../../../worker-pallets/parentchain", default-features = false }

[dev-dependencies]
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

[features]
default = ["std"]
evm = ["ita-sgx-runtime/evm"]
sgx = [
    "sgx_tstd",
    "itp-sgx-externalities/sgx",
    "sp-io/sgx",
    "itp-node-api/sgx",
    # litentry
    "litentry-primitives/sgx",
    "lc-stf-task-sender/sgx",
    "itp-node-api-metadata-provider/sgx",
]
std = [
    # crates.io
    "codec/std",
    "log/std",
    # local
    "ita-sgx-runtime/std",
    "itp-hashing/std",
    "itp-sgx-externalities/std",
    "itp-stf-interface/std",
    "itp-storage/std",
    "itp-types/std",
    "itp-node-api/std",
    "itp-node-api-metadata/std",
    # substrate
    "sp-core/std",
    "pallet-balances/std",
    "pallet-sudo/std",
    "frame-system/std",
    "frame-support/std",
    "sp-runtime/std",
    # scs/integritee
    "pallet-parentchain/std",
    "sp-io/std",
    # litentry
    "litentry-primitives/std",
    "lc-stf-task-sender/std",
    "itp-node-api-metadata-provider/std",
]
test = []
development = [
    "litentry-macros/development",
    "ita-sgx-runtime/development",
]
