[package]
name = "lc-vc-task-receiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# std dependencies
futures = { version = "0.3.8", optional = true }
thiserror = { version = "1.0.26", optional = true }

# sgx dependencies
futures_sgx = { package = "futures", git = "https://github.com/mesalock-linux/futures-rs-sgx", optional = true, features = ["thread-pool"] }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "master", features = ["net", "thread"], optional = true }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
hex = { version = "0.4.3", default-features = false }
log = { version = "0.4", default-features = false }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# internal dependencies
ita-sgx-runtime = { path = "../../../../app-libs/sgx-runtime", default-features = false }
ita-stf = { path = "../../../../app-libs/stf", default-features = false }
itp-enclave-metrics = { path = "../../../../core-primitives/enclave-metrics", default-features = false }
itp-extrinsics-factory = { path = "../../../../core-primitives/extrinsics-factory", default-features = false }
itp-node-api = { path = "../../../../core-primitives/node-api", default-features = false }
itp-ocall-api = { path = "../../../../core-primitives/ocall-api", default-features = false }
itp-sgx-crypto = { path = "../../../../core-primitives/sgx/crypto", default-features = false }
itp-sgx-externalities = { path = "../../../../core-primitives/substrate-sgx/externalities", default-features = false }
itp-stf-executor = { path = "../../../../core-primitives/stf-executor", default-features = false }
itp-stf-primitives = { path = "../../../../core-primitives/stf-primitives", default-features = false }
itp-stf-state-handler = { path = "../../../../core-primitives/stf-state-handler", default-features = false }
itp-storage = { path = "../../../../core-primitives/storage", default-features = false }
itp-top-pool-author = { path = "../../../../core-primitives/top-pool-author", default-features = false }
itp-types = { path = "../../../../core-primitives/types", default-features = false }
itp-utils = { path = "../../../../core-primitives/utils", default-features = false }

frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
lc-assertion-build = { path = "../../assertion-build", default-features = false }
lc-assertion-build-v2 = { path = "../../assertion-build-v2", default-features = false }
lc-credentials = { path = "../../credentials", default-features = false }
lc-data-providers = { path = "../../data-providers", default-features = false }
lc-dynamic-assertion = { path = "../../dynamic-assertion", default-features = false }
lc-evm-dynamic-assertions = { path = "../../evm-dynamic-assertions", default-features = false }
lc-parachain-extrinsic-task-sender = { path = "../../parachain-extrinsic-task/sender", default-features = false }
lc-stf-task-receiver = { path = "../../stf-task/receiver", default-features = false }
lc-stf-task-sender = { path = "../../stf-task/sender", default-features = false }
lc-vc-task-sender = { path = "../sender", default-features = false }
litentry-macros = { path = "../../../../../primitives/core/macros", default-features = false }
litentry-primitives = { path = "../../../primitives", default-features = false }
pallet-identity-management-tee = { path = "../../../pallets/identity-management", default-features = false }

[features]
default = ["std"]
sgx = [
    "futures_sgx",
    "sgx_tstd",
    "ita-stf/sgx",
    "itp-sgx-externalities/sgx",
    "itp-stf-executor/sgx",
    "itp-stf-state-handler/sgx",
    "itp-top-pool-author/sgx",
    "sp-core/full_crypto",
    "litentry-primitives/sgx",
    "lc-assertion-build/sgx",
    "lc-assertion-build-v2/sgx",
    "lc-credentials/sgx",
    "lc-data-providers/sgx",
    "lc-stf-task-receiver/sgx",
    "lc-stf-task-sender/sgx",
    "itp-extrinsics-factory/sgx",
    "itp-node-api/sgx",
    "itp-storage/sgx",
    "lc-vc-task-sender/sgx",
    "lc-dynamic-assertion/sgx",
    "lc-evm-dynamic-assertions/sgx",
]
std = [
    "futures",
    "log/std",
    "ita-stf/std",
    "itp-types/std",
    "itp-top-pool-author/std",
    "itp-stf-executor/std",
    "itp-stf-state-handler/std",
    "itp-stf-primitives/std",
    "sp-core/std",
    "litentry-primitives/std",
    "lc-assertion-build/std",
    "lc-assertion-build-v2/std",
    "ita-sgx-runtime/std",
    "frame-support/std",
    "lc-credentials/std",
    "lc-data-providers/std",
    "lc-stf-task-receiver/std",
    "lc-stf-task-sender/std",
    "itp-extrinsics-factory/std",
    "itp-node-api/std",
    "itp-storage/std",
    "lc-vc-task-sender/std",
    "lc-dynamic-assertion/std",
    "lc-evm-dynamic-assertions/std",
]
development = [
    "ita-stf/development",
    "lc-data-providers/development",
    "litentry-macros/development",
    "pallet-identity-management-tee/development",
]
