[package]
authors = ['Trust Computing GmbH <info@litentry.com>']
description = 'Proc-macros used by Litentry crates.'
name = "litentry-proc-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
cargo_toml = "0.19"
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "visit-mut"] }
