version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["automated-pr"]
    # Handle updates for crates from github.com/paritytech/substrate manually.
    ignore:
      - dependency-name: "substrate-*"
      - dependency-name: "sc-*"
      - dependency-name: "sp-*"
      - dependency-name: "frame-*"
      - dependency-name: "fork-tree"
      - dependency-name: "remote-externalities"
      - dependency-name: "pallet-*"
      - dependency-name: "beefy-*"
      - dependency-name: "try-runtime-*"
      - dependency-name: "test-runner"
      - dependency-name: "generate-bags"
      - dependency-name: "sub-tokens"
      - dependency-name: "polkadot-*"
      - dependency-name: "xcm*"
      - dependency-name: "kusama-*"
      - dependency-name: "westend-*"
      - dependency-name: "litentry-*"
    reviewers:
      - "litentry/parachain"
    schedule:
      interval: "weekly"

  - package-ecosystem: github-actions
    directory: '/'
    labels: ["automated-pr"]
    reviewers:
      - "litentry/parachain"
    schedule:
      interval: "weekly"

    # handle ts-tests dependencies manually before we find a way to merge
    # the dependabot PRs
