# This is used by the action https://github.com/dorny/paths-filter to run jobs conditionally
# Put all defined set of files here, similar to https://github.com/getsentry/sentry/blob/master/.github/workflows/getsentry-dispatch.yml

parachain_src: &parachain_src
  - 'parachain/node/**'
  - 'parachain/pallets/**'
  - 'primitives/**'
  - 'parachain/runtime/**'
  - 'parachain/docker/Dockerfile'
  - 'parachain/Cargo.*'
  - 'parachain/rust-toolchain.toml'
  - 'parachain/scripts/build-docker.sh'

parachain_test: &parachain_test
  - 'parachain/ts-tests/**'
  - 'parachain/docker/**'
  - 'parachain/scripts/build-bridge.sh'
  - 'parachain/scripts/launch-network.sh'
  - 'parachain/scripts/launch-bridge.sh'

coverage_src: &coverage_src
  - *parachain_src
  - '.github/workflows/coverage.yml'

identity_src: &identity_src
  - 'tee-worker/identity/**/*.rs'
  - 'tee-worker/identity/**/Cargo.toml'
  - 'tee-worker/identity/**/Cargo.lock'
  - 'tee-worker/identity/**/rust-toolchain.toml'
  - 'tee-worker/identity/build.Dockerfile'
  - 'tee-worker/identity/enclave-runtime/**'

identity_test: &identity_test
  - 'tee-worker/identity/ts-tests/**'
  - 'tee-worker/identity/cli/*.sh'
  - 'parachain/docker/**'
  - 'tee-worker/identity/docker/*.yml'
  - 'tee-worker/identity/litentry/core/assertion-build/src/dynamic/contracts/**'

bitacross_src: &bitacross_src
  - 'tee-worker/bitacross/**/*.rs'
  - 'tee-worker/bitacross/**/Cargo.toml'
  - 'tee-worker/bitacross/**/Cargo.lock'
  - 'tee-worker/bitacross/**/rust-toolchain.toml'
  - 'tee-worker/bitacross/build.Dockerfile'
  - 'tee-worker/bitacross/enclave-runtime/**'

bitacross_test: &bitacross_test
  - 'tee-worker/bitacross/ts-tests/**'
  - 'tee-worker/bitacross/cli/*.sh'
  - 'parachain/docker/**'
  - 'tee-worker/bitacross/docker/*.yml'
