[package]
authors = ['Trust Computing GmbH <info@litentry.com>']
description = 'Litentry hex utils'
name = "litentry-hex-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = { workspace = true, features = ["alloc"] }

[dev-dependencies]
parity-scale-codec = { workspace = true }

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "hex/std",
]
