[package]
name = "intention-executor"
version = "0.1.0"
edition.workspace = true

[dependencies]
alloy = { workspace = true, features = ["contract", "signer-local", "rpc", "rpc-types"] }
async-trait = { workspace = true }
executor-core = { path = "../../executor-core" }
log = { workspace = true }
