[package]
name = "its-state"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", workspace = true, features = ["chain-error"] }
frame-support = { workspace = true }
log = { workspace = true }

sgx_tstd = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
thiserror_sgx = { workspace = true, optional = true }

itp-sgx-externalities = { workspace = true }
itp-storage = { workspace = true }
its-primitives = { workspace = true }
sp-io = { path = "../../../common/core-primitives/substrate-sgx/sp-io", default-features = false, features = ["disable_oom", "disable_panic_handler", "disable_allocator"], optional = true }

sp-core = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
    "log/std",
    # substrate
    "sp-core/std",
    # local crates
    "itp-sgx-externalities/std",
    "itp-storage/std",
    "its-primitives/std",
    "sp-io/std",
    # optional std crates
    "codec/std",
    "thiserror",
    "sp-runtime/std",
]
sgx = [
    # teaclave
    "sgx_tstd",
    # local crates
    "itp-sgx-externalities/sgx",
    "itp-storage/sgx",
    "sp-io/sgx",
    # sgx versions of std crates
    "thiserror_sgx",
]
