[package]
name = "parentchain-primitives"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
executor-core = { path = "../../executor-core" }

[lints]
workspace = true
