[package]
name = "itp-node-api-metadata"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
derive_more = { version = "0.99.5" }

# local
itp-api-client-types = { default-features = false, path = "../api-client-types" }
itp-stf-primitives = { default-features = false, path = "../../stf-primitives" }

# substrate
sp-core = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.42" }

[features]
default = ["std"]
std = [
    "codec/std",
    "itp-api-client-types/std",
    "sp-core/std",
    "itp-stf-primitives/std",
]

# used for unit testing only!
mocks = []
