[package]
authors = ['Trust Computing GmbH <info@litentry.com>']
edition = '2021'
homepage = 'https://litentry.com'
name = 'pallet-bridge-common'
repository = 'https://github.com/litentry/litentry-pallets'
version = '0.1.0'

[dependencies]
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }

frame-support = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
    "frame-support/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
]
std = [
    "scale-info/std",
    "parity-scale-codec/std",
    "frame-support/std",
    "sp-runtime/std",
]
try-runtime = [
    "frame-support/try-runtime",
    "sp-runtime/try-runtime",
]
