[package]
name = "oauth-providers"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
