[package]
name = "id-itc-parentchain"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", workspace = true, features = ["chain-error"] }

sp-runtime = { workspace = true }

itc-parentchain-block-import-dispatcher = { package = "id-itc-parentchain-block-import-dispatcher", path = "../block-import-dispatcher", default-features = false }
itc-parentchain-block-importer = { package = "id-itc-parentchain-block-importer", path = "../block-importer", default-features = false }
itc-parentchain-indirect-calls-executor = { package = "id-itc-parentchain-indirect-calls-executor", path = "../indirect-calls-executor", default-features = false }
itc-parentchain-light-client = { workspace = true }
itp-types = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-runtime/std",
    "itc-parentchain-block-import-dispatcher/std",
    "itc-parentchain-block-importer/std",
    "itc-parentchain-indirect-calls-executor/std",
    "itc-parentchain-light-client/std",
    "itp-types/std",
]
sgx = [
    "itc-parentchain-block-import-dispatcher/sgx",
    "itc-parentchain-block-importer/sgx",
    "itc-parentchain-indirect-calls-executor/sgx",
    "itc-parentchain-light-client/sgx",
]
mocks = [
    "itc-parentchain-block-import-dispatcher/mocks",
    "itc-parentchain-light-client/mocks",
]
test = [
    "mocks",
    "itc-parentchain-light-client/test",
]
