[package]
name = "bitacross-cli"
version = "0.0.1"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
base58 = { workspace = true }
chrono = "*"
clap = { version = "=4.1.0", features = ["derive"] }
codec = { workspace = true, features = ["std"] }
env_logger = { workspace = true }
hdrhistogram = "7.5.0"
hex = { workspace = true, features = ["std"] }
log = { workspace = true, features = ["std"] }
rand = "0.8.5"
rayon = "1.5.1"
regex = "1.9.5"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { workspace = true, features = ["std"] }
serde_json = "1.0"
thiserror = { workspace = true, features = ["std"] }
urlencoding = "2.1.3"

sgx_crypto_helper = { workspace = true }
substrate-api-client = { workspace = true }
substrate-client-keystore = { git = "https://github.com/scs/substrate-api-client.git", branch = "polkadot-v0.9.42-tag-v0.14.0" }

sp-application-crypto = { workspace = true, features = ["std"] }
sp-core = { workspace = true, features = ["std"] }
sp-keyring = { workspace = true, features = ["std"] }
sp-keystore = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }

ita-stf = { path = "../app-libs/stf" }
ita-parentchain-interface = { path = "../app-libs/parentchain-interface" }
bc-musig2-ceremony = { path = "../bitacross/core/bc-musig2-ceremony" }
lc-direct-call = { path = "../litentry/core/direct-call" }

itc-rpc-client = { workspace = true }
itp-node-api = { workspace = true, features = ["std"] }
itp-rpc = { workspace = true, features = ["std"] }
itp-sgx-crypto = { workspace = true, features = ["std"] }
itp-stf-primitives = { workspace = true, features = ["std"] }
itp-types = { workspace = true, features = ["std"] }
itp-utils = { workspace = true, features = ["std"] }
litentry-primitives = { workspace = true, features = ["std"] }

[features]
default = []
offchain-worker = []
development = []
# dcap feature flag is not used in this crate, but for easier build purposes only it present here as well
dcap = []
