[package]
name = "parentchain-rpc-client"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
log = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-encode = { workspace = true }
serde_json = { workspace = true }
subxt = { workspace = true }
subxt-core = { workspace = true }
tokio = { workspace = true }

# Local dependencies
executor-primitives = { workspace = true }
parentchain-api-interface = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }

[lints]
workspace = true
