[package]
name = "accounting-contract-client"
version = "0.1.0"
edition.workspace = true

[dependencies]
alloy = { workspace = true, features = ["contract", "signer-local", "rpc", "rpc-types", "eips"] }
async-trait = { workspace = true }
ethereum-rpc = { workspace = true }
log = { workspace = true }
mockall = { workspace = true }

[lints]
workspace = true

[features]
mocks = []
