[package]
name = "parentchain-listener"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
hex = "0.4.3"
log = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
subxt = { workspace = true }
subxt-core = { workspace = true }
subxt-signer = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

# Local dependencies
executor-core = { workspace = true }
parentchain-api-interface = { workspace = true }
parentchain-rpc-client = { workspace = true }
parentchain-signer = { workspace = true }
primitives = { workspace = true }
storage = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }

[lints]
workspace = true

[features]
gramine-quote = []
