[package]
name = "parentchain-listener"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-encode = { workspace = true }
sp-core = { workspace = true }
subxt = { workspace = true }
subxt-core = { workspace = true }
subxt-signer = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

executor-core = { workspace = true }
parentchain-api-interface = { workspace = true }
parentchain-primitives = { workspace = true }
parentchain-rpc-client = { workspace = true }
executor-storage = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }

[lints]
workspace = true

[features]
gramine-quote = []
