[package]
name = "itp-utils"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
homepage = "https://litentry.com/"
repository = "https://github.com/litentry/litentry-parachain"
license = "Apache-2.0"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
litentry-hex-utils = { path = "../../../primitives/hex", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "hex/std",
]
