[package]
name = "its-storage"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# crate.io
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
log = "0.4"
parking_lot = "0.12.1"
rocksdb = { version = "0.20.1", default_features = false }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

# integritee
itp-settings = { path = "../../core-primitives/settings" }

its-primitives = { path = "../primitives" }

# Substrate dependencies
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

[dev-dependencies]
# crate.io
mockall = "0.11"
temp-dir = "0.1"
# local
itp-time-utils = { path = "../../core-primitives/time-utils" }
its-test = { path = "../test" }
itp-types = { path = "../../core-primitives/types" }

[features]
mocks = []
