[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
accounting_contract = "31weKQJQA9ZFYaVdnjtAXUoEGPW8UUFC5TEvgPJugAub"

[registry]
url = "https://api.apr.dev"

[provider]
url = "http://localhost:8899"
cluster = "Localnet"
wallet = "test-account.json"

[scripts]
test = "cargo test"
