[package]
authors = ['Trust Computing GmbH <info@litentry.com>']
version = "0.1.0"
edition = "2021"
homepage = 'https://litentry.com'
name = 'pallet-omni-account-runtime-api'
repository = 'https://github.com/litentry/heima'

[dependencies]
parity-scale-codec = { workspace = true }
sp-api = { workspace = true }

core-primitives = { workspace = true }
pallet-omni-account = { workspace = true }

[features]
default = ["std"]
std = [
    "core-primitives/std",
    "pallet-omni-account/std",
    "parity-scale-codec/std",
    "sp-api/std",
]
