[package]
name = "lc-dynamic-assertion"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition = "2021"

[dependencies]
litentry-primitives = { workspace = true }
sgx_tstd = { workspace = true, optional = true }

[features]
default = ["std"]
sgx = [
    "sgx_tstd",
    "litentry-primitives/sgx",
]
std = [
    "litentry-primitives/std",
]
