[package]
name = "itp-stf-interface"
version = "0.8.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
codec = { version = "3.0.0", default-features = false, features = ["derive"], package = "parity-scale-codec" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

itp-node-api-metadata = { path = "../node-api/metadata", default-features = false, features = ["mocks"] }
itp-node-api-metadata-provider = { path = "../node-api/metadata-provider", default-features = false }
itp-ocall-api = { path = "../ocall-api", default-features = false }
itp-stf-primitives = { path = "../stf-primitives", default-features = false }
itp-sgx-crypto = { path = "../sgx/crypto", default-features = false }
itp-types = { default-features = false, path = "../types" }

[features]
default = ["std"]
std = [
    "itp-node-api-metadata/std",
    "itp-node-api-metadata-provider/std",
    "itp-stf-primitives/std",
    "itp-types/std",
    "itp-ocall-api/std",
    "itp-sgx-crypto/std",
]
sgx = []
mocks = [
    "itp-ocall-api/mocks",
    "itp-sgx-crypto/mocks",
]
