[package]
name = "executor-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
log = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
