[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = '2021'
name = 'runtime-common'
version = '0.9.17'

[dependencies]
log = { workspace = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }

frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-state-machine = { workspace = true }
sp-std = { workspace = true }

pallet-assets = { workspace = true }
pallet-authorship = { workspace = true }
pallet-balances = { workspace = true }
pallet-collective = { workspace = true }
pallet-membership = { workspace = true }
pallet-multisig = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-treasury = { workspace = true }
pallet-vesting = { workspace = true }

cumulus-pallet-parachain-system = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-primitives-parachain-inherent = { workspace = true }
parachain-info = { workspace = true }

pallet-xcm = { workspace = true }
xcm = { workspace = true }
xcm-builder = { workspace = true }
xcm-executor = { workspace = true }
xcm-simulator = { workspace = true, optional = true }

orml-xtokens = { workspace = true }

polkadot-parachain = { workspace = true }
polkadot-primitives = { workspace = true }
polkadot-runtime-parachains = { workspace = true }

core-primitives = { workspace = true }
pallet-asset-manager = { workspace = true }
pallet-extrinsic-filter = { workspace = true }
pallet-group = { workspace = true }
pallet-teebag = { workspace = true }

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "log/std",
    "sp-core/std",
    "sp-io/std",
    "sp-std/std",
    "sp-runtime/std",
    "sp-state-machine/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-assets/std",
    "pallet-authorship/std",
    "pallet-balances/std",
    "pallet-collective/std",
    "pallet-group/std",
    "pallet-multisig/std",
    "pallet-membership/std",
    "pallet-transaction-payment/std",
    "pallet-treasury/std",
    "pallet-vesting/std",
    "polkadot-parachain/std",
    "polkadot-primitives/std",
    "polkadot-runtime-parachains/std",
    "cumulus-primitives-parachain-inherent/std",
    "cumulus-pallet-parachain-system/std",
    "cumulus-primitives-core/std",
    "pallet-xcm/std",
    "xcm/std",
    "xcm-builder/std",
    "xcm-executor/std",
    "parachain-info/std",
    "core-primitives/std",
    "pallet-asset-manager/std",
    "pallet-extrinsic-filter/std",
    "pallet-teebag/std",
    "orml-xtokens/std",
]

runtime-benchmarks = [
    "pallet-group/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "pallet-teebag/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]

try-runtime = [
    "pallet-assets/try-runtime",
    "pallet-authorship/try-runtime",
    "pallet-balances/try-runtime",
    "pallet-group/try-runtime",
    "pallet-teebag/try-runtime",
    "pallet-transaction-payment/try-runtime",
    "pallet-treasury/try-runtime",
    "frame-support/try-runtime",
]

tests = [
    "std",
    "xcm-simulator",
]
