[package]
name = "bc-musig2-ceremony"
authors = ["Trust Computing GmbH <info@litentry.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# std dependencies
musig2 = { package = "musig2", branch = "master", git = "https://github.com/kziemianek/musig2.git", optional = true, features = ["k256"] }
rand = { version = "0.8.5", optional = true }

# sgx dependencies
musig2_sgx = { package = "musig2", git = "https://github.com/kailai-wang/musig2.git", branch = "use-sha2-0.8", optional = true, features = ["k256"] }
sgx_rand = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "master", optional = true, features = ["net", "thread"] }

# no-std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
k256 = { version = "0.13.3", default-features = false, features = ["ecdsa-core", "schnorr", "alloc"] }
log = { version = "0.4", default-features = false }

# local
bc-enclave-registry = { path = "../bc-enclave-registry", default-features = false }
itc-direct-rpc-client = { path = "../../../core/direct-rpc-client", default-features = false }
itp-rpc = { path = "../../../core-primitives/rpc", default-features = false }
itp-sgx-crypto = { path = "../../../core-primitives/sgx/crypto", default-features = false }
itp-types = { path = "../../../core-primitives/types", default-features = false }
litentry-primitives = { path = "../../../litentry/primitives", default-features = false }

[dev-dependencies]
rand = { version = "0.8.5" }
signature = "2.1.0"

[features]
default = ["std"]
sgx-test = ["sgx"]
std = [
    "musig2",
    "itc-direct-rpc-client/std",
    "log/std",
    "itp-types/std",
    "bc-enclave-registry/std",
    "litentry-primitives/std",
    "itp-rpc/std",
    "itp-sgx-crypto/std",
    "rand",
]
sgx = [
    "sgx_tstd",
    "musig2_sgx",
    "itc-direct-rpc-client/sgx",
    "bc-enclave-registry/sgx",
    "litentry-primitives/sgx",
    "itp-rpc/sgx",
    "itp-sgx-crypto/sgx",
    "sgx_rand",
]
