[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-stf-task-receiver"
version = "0.1.0"

[dependencies]
# std dependencies
futures = { version = "0.3.8", optional = true }
thiserror = { version = "1.0.26", optional = true }

# sgx dependencies
futures_sgx = { package = "futures", git = "https://github.com/mesalock-linux/futures-rs-sgx", optional = true }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "master", features = ["net", "thread"], optional = true }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
hex = { version = "0.4.3", default-features = false }
log = { version = "0.4", default-features = false }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# internal dependencies
ita-stf = { path = "../../../../app-libs/stf", default-features = false }
itc-peer-top-broadcaster = { path = "../../../../core/peer-top-broadcaster", default-features = false }
itp-enclave-metrics = { path = "../../../../core-primitives/enclave-metrics", default-features = false }
itp-ocall-api = { path = "../../../../core-primitives/ocall-api", default-features = false }
itp-sgx-crypto = { path = "../../../../core-primitives/sgx/crypto", default-features = false }
itp-sgx-externalities = { path = "../../../../core-primitives/substrate-sgx/externalities", default-features = false }
itp-stf-executor = { path = "../../../../core-primitives/stf-executor", default-features = false }
itp-stf-primitives = { path = "../../../../core-primitives/stf-primitives", default-features = false }
itp-stf-state-handler = { path = "../../../../core-primitives/stf-state-handler", default-features = false }
itp-top-pool-author = { path = "../../../../core-primitives/top-pool-author", default-features = false }
itp-types = { path = "../../../../core-primitives/types", default-features = false }
itp-utils = { path = "../../../../core-primitives/utils", default-features = false }

# litentry
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
ita-sgx-runtime = { path = "../../../../app-libs/sgx-runtime", default-features = false }
lc-assertion-build = { path = "../../assertion-build", default-features = false }
lc-assertion-build-v2 = { path = "../../assertion-build-v2", default-features = false }
lc-credentials = { path = "../../credentials", default-features = false }
lc-data-providers = { path = "../../data-providers", default-features = false }
lc-dynamic-assertion = { path = "../../dynamic-assertion", default-features = false }
lc-evm-dynamic-assertions = { path = "../../evm-dynamic-assertions", default-features = false }
lc-identity-verification = { path = "../../identity-verification", default-features = false }
lc-stf-task-sender = { path = "../sender", default-features = false }
litentry-primitives = { path = "../../../primitives", default-features = false }

[dev-dependencies]
sgx_crypto_helper = { version = "1.1.6", git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "master" }
itp-test = { path = "../../../../core-primitives/test" }
itp-top-pool-author = { path = "../../../../core-primitives/top-pool-author", features = ["mocks"] }
itp-top-pool = { path = "../../../../core-primitives/top-pool", features = ["mocks"] }
itp-stf-executor = { path = "../../../../core-primitives/stf-executor", features = ["mocks"] }
itp-sgx-crypto = { path = "../../../../core-primitives/sgx/crypto", features = ["mocks"] }
base58 = "0.2"
jsonrpc-core = { version = "18" }
lazy_static = { version = "1.1.0" }
hex = "0.4.2"

[features]
default = ["std"]
sgx = [
    "futures_sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "ita-stf/sgx",
    "itc-peer-top-broadcaster/sgx",
    "itp-sgx-externalities/sgx",
    "itp-stf-executor/sgx",
    "itp-stf-state-handler/sgx",
    "itp-top-pool-author/sgx",
    "sp-core/full_crypto",
    "litentry-primitives/sgx",
    "lc-stf-task-sender/sgx",
    "lc-identity-verification/sgx",
    "lc-assertion-build/sgx",
    "lc-assertion-build-v2/sgx",
    "lc-credentials/sgx",
    "lc-data-providers/sgx",
    "lc-evm-dynamic-assertions/sgx",
    "lc-dynamic-assertion/sgx",
]
std = [
    "futures",
    "log/std",
    "thiserror",
    "ita-stf/std",
    "itc-peer-top-broadcaster/std",
    "itp-types/std",
    "itp-top-pool-author/std",
    "itp-utils/std",
    "itp-stf-executor/std",
    "itp-stf-state-handler/std",
    "itp-stf-primitives/std",
    "sp-core/std",
    "litentry-primitives/std",
    "lc-stf-task-sender/std",
    "lc-identity-verification/std",
    "lc-assertion-build/std",
    "lc-assertion-build-v2/std",
    "ita-sgx-runtime/std",
    "frame-support/std",
    "lc-credentials/std",
    "lc-data-providers/std",
    "lc-evm-dynamic-assertions/std",
    "lc-dynamic-assertion/std",
]
