services:
  omni-executor:
    env_file:
      - ../.env.test
    command: ["executor-worker", "run", "--parentchain-sync", "--enable-mock-server"]
    ports:
      - "2100:2100"
      - "3456:3456"
      - "9090:9090"