services:
  omni-executor:
    image: litentry/omni-executor:latest
    container_name: omni-executor
    build:
      context: ${PWD}/../../
      dockerfile: tee-worker/omni-executor/Dockerfile
      target: executor-worker
    volumes:
      - ../local/keystore:/local/keystore
    env_file:
      - ../.env.test
    environment:
      - RUST_LOG=${RUST_LOG:-debug}
    depends_on:
      ethereum-node:
        condition: service_started
      heima-node:
        condition: service_healthy
        restart: true
      mock-server:
        condition: service_started
    command: ["executor-worker", "run", "ws://heima-node:9944", "http://ethereum-node:8545", "https://api.devnet.solana.com", "pumpx-signer-url", "ws://omni-executor:2100", "bsc-url", "bsc-testnet-url", "--parentchain-sync"]
    privileged: true
    restart: unless-stopped
    networks:
      - litentry-test-network
    ports:
      - "2100:2100"
      - "9090:9090"
    healthcheck:
      test: [ "CMD-SHELL", "curl -X POST -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"method\":\"omni_getHealth\",\"id\":1}' http://localhost:2100 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
  ethereum-node:
    image: ghcr.io/foundry-rs/foundry
    container_name: ethereum-node
    command:
      - "anvil --host 0.0.0.0 --block-time 1"
    ports:
      - "8545:8545"
  heima-node:
    image: litentry/heima:latest
    container_name: heima-node
    ports:
      - "9944:9944"
    command: ["--dev", "--rpc-external", "--pool-type=fork-aware", "--rpc-port", "9944"]
    networks:
      - litentry-test-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9944"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval:  5s
  mock-server:
    image: litentry/mock-server:latest
    container_name: mock-server
    command: ["mock-server"]
    networks:
      - litentry-test-network
    environment:
      - RUST_LOG=${RUST_LOG:-debug}
    ports:
      - "3456:3456"

networks:
  litentry-test-network:
    driver: bridge
