services:
  jsonrpc-mock-tests:
    image: litentry/omni-executor:latest
    container_name: litentry-jsonrpc-mock-tests
    volumes:
      - ../ts-tests:/ts-tests
      - ../../client-api:/client-api
      - ../cli:/usr/local/executor-worker-cli
    build:
      context: ${PWD}/../../
      dockerfile: tee-worker/omni-executor/Dockerfile
      target: executor-worker
    depends_on:
      omni-executor:
        condition: service_healthy
        restart: true
    networks:
      - litentry-test-network
    entrypoint: "sh -c '/usr/local/executor-worker-cli/ts_jsonrpc_mock_test.sh 3>&1' "
    restart: "no"
networks:
  litentry-test-network:
    driver: bridge 