services:
    omni-account-test:
        image: litentry/omni-executor:latest
        container_name: litentry-omni-account-test
        volumes:
            - ../ts-tests:/ts-tests
            - ../../client-api:/client-api
            - ../ts-tests/cli:/usr/local/omni-executor-cli
        build:
            context: ${PWD}/../../
            dockerfile: tee-worker/omni-executor/Dockerfile
            target: omni-executor
        depends_on:
          omni-executor:
            condition: service_healthy
            restart: true
        networks:
            - litentry-test-network
        entrypoint: "sh -c '/usr/local/omni-executor-cli/ts_integration_test.sh omni_account.test.ts 3>&1' "
        restart: "no"
networks:
    litentry-test-network:
        driver: bridge
