services:
  omni-client-sdk-test:
    image: litentry/omni-executor:latest
    container_name: litentry-omni-client-sdk-test
    volumes:
      - ../client-sdk:/client-sdk
      - ../../client-api:/client-api
      - ../ts-tests/cli:/usr/local/omni-executor-cli
    build:
      context: ${PWD}/../../
      dockerfile: tee-worker/omni-executor/Dockerfile
      target: omni-executor
    depends_on:
      omni-executor:
        condition: service_healthy
        restart: true
    networks:
      - litentry-test-network
    entrypoint: "sh -c '/usr/local/omni-executor-cli/ts_client_sdk_test.sh 3>&1' "
    restart: "no"
networks:
  litentry-test-network:
    driver: bridge
