services:
  submit-user-op-tests:
    image: litentry/omni-executor:latest
    container_name: litentry-submit-user-op-tests
    volumes:
      - ../ts-tests:/ts-tests
      - ../../client-api:/client-api
      - ../ts-tests/cli:/usr/local/omni-executor-cli
      - shared-data:/shared
    build:
      context: ${PWD}/../../
      dockerfile: tee-worker/omni-executor/Dockerfile
      target: omni-executor
    depends_on:
      omni-executor:
        condition: service_healthy
        restart: true
      aa-contracts-deploy:
        condition: service_completed_successfully
    networks:
      - litentry-test-network
    entrypoint: "sh -c '/usr/local/omni-executor-cli/ts_submit_user_op_test.sh 3>&1' "
    restart: "no"
volumes:
  shared-data:
networks:
  litentry-test-network:
    driver: bridge