[workspace]
members = [
    "crypto",
    "native-call-executor",
    "executor-core",
    "executor-worker",
    "ethereum/intent-executor",
    "parentchain/listener",
    "parentchain/api-interface",
    "parentchain/storage",
    "rpc-server",
    "solana/intent-executor",
]

resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
log = "0.4.22"
tokio = "1.43.0"
async-trait = "0.1.82"
env_logger = "0.11.5"
scale-encode = "0.7.1"
parity-scale-codec = "3.6.12"
alloy = "0.3.6"
clap = "4.5.17"
solana-sdk = "2.1.5"
solana-client = "2.1.5"
subxt = "0.38.0"
subxt-core = "0.38.0"
subxt-signer = { version = "0.38.0", features = ["subxt"] }
jsonrpsee = { version = "0.24", features = ["server"] }
rsa = "0.9.7"
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
ring = "0.17.8"

rpc-server = { path = "rpc-server" }
crypto = { path = "crypto" }
native-call-executor = { path = "native-call-executor" }
executor-core = { path = "executor-core" }
parentchain-api-interface = { path = "parentchain/api-interface" }

[workspace.lints.clippy]
result_unit_err = "allow"
