[workspace]
members = [
    "executor-core",
    "executor-worker",
    "parentchain/listener",
    "parentchain/api-interface",
    "parentchain/storage",
    "ethereum/intent-executor",
    "solana/intent-executor",
    "rpc",
]

resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
log = "0.4.22"
tokio = "1.43.0"
async-trait = "0.1.82"
env_logger = "0.11.5"
scale-encode = "0.7.1"
parity-scale-codec = "3.6.12"
alloy = "0.3.6"
clap = "4.5.17"
solana-sdk = "2.1.5"
solana-client = "2.1.5"
subxt = "0.38.0"
subxt-core = "0.38.0"
subxt-signer = { version = "0.38.0", features = ["subxt"] }
jsonrpsee = { version = "0.24", features = ["server"] }
rsa = { version = "0.9.7", features = ["serde"] }
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"

rpc = { path = "rpc" }

[workspace.lints.clippy]
result_unit_err = "allow"
