[workspace]
members = [
    "executor-core",
    "executor-worker",
    "parentchain/listener",
    "parentchain/api-interface",
    "parentchain/storage",
    "ethereum/intent-executor",
    "solana/intent-executor",
]

resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
alloy = "0.3.6"
async-trait = "0.1.82"
clap = "4.5.17"
env_logger = "0.11.5"
hex = "0.4.3"
log = "0.4.22"
parity-scale-codec = "3.6.12"
regex = "1.7"
scale-encode = "0.7.1"
scale-encode = "0.7.1"
solana-client = "2.1.5"
solana-sdk = "2.1.5"
sp-core = "35.0.0"
subxt = "0.38.0"
subxt-core = "0.38.0"
subxt-signer = { version = "0.38.0", features = ["subxt"] }
tokio = "1.40.0"

[workspace.lints.clippy]
result_unit_err = "allow"
