[workspace]
members = [
    "crypto",
    "native-call-executor",
    "executor-core",
    "executor-worker",
    "ethereum/intent-executor",
    "ethereum/intent-executor",
    "parentchain/listener",
    "parentchain/api-interface",
    "parentchain/rpc-client",
    "parentchain/storage",
    "parentchain/primitives",
    "rpc-server",
    "solana/intent-executor",
]

resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
log = "0.4.22"
tokio = "1.43.0"
async-trait = "0.1.82"
env_logger = "0.11.5"
scale-encode = "0.10.0"
parity-scale-codec = "3.6.12"
alloy = "0.3.6"
clap = "4.5.17"
solana-sdk = "2.1.5"
solana-client = "2.1.5"
subxt = "0.38.0"
subxt-core = "0.38.0"
subxt-signer = { version = "0.38.0", features = ["subxt"] }
jsonrpsee = { version = "0.24", features = ["server"] }
rsa = "0.9.7"
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
ring = "0.17.8"
scale-info = "2.11.6"
sp-core = "35.0.0"
secp256k1 = "=0.29.1"
bitcoin = "0.32.5"
base64 = "0.22.1"

crypto = { path = "crypto" }
rpc-server = { path = "rpc-server" }
native-call-executor = { path = "native-call-executor" }
executor-core = { path = "executor-core" }
parentchain-api-interface = { path = "parentchain/api-interface" }
parentchain-primitives = { path = "parentchain/primitives" }
sp-state-machine = { version = "0.44.0", features = ["std"] }
frame-support = { version = "39.0.0", features = ["std"] }
ethereum-intent-executor = { path = "ethereum/intent-executor" }
solana-intent-executor = { path = "solana/intent-executor" }
parentchain-listener = { path = "parentchain/listener" }
parentchain-rpc-client = { path = "parentchain/rpc-client" }
parentchain-storage = { path = "parentchain/storage" }
heima-primitives = { package = "core-primitives", path = "../../common/primitives/core" }

[workspace.lints.clippy]
result_unit_err = "allow"
