# syntax=docker/dockerfile:1

### Local binary deployment image
##################################################
FROM ubuntu:24.04 AS executor-worker

ENV BIN_DIR=/usr/local/bin
WORKDIR $BIN_DIR

RUN apt update && apt install -y ca-certificates curl

# Copy the pre-built binary from local target directory
COPY target/release/executor-worker $BIN_DIR/executor-worker
COPY local/keystore $BIN_DIR/local/keystore

RUN chmod +x $BIN_DIR/executor-worker
RUN ls -al $BIN_DIR
RUN ldd $BIN_DIR/executor-worker && $BIN_DIR/executor-worker --version

CMD ["executor-worker"]