# syntax=docker/dockerfile:1

### Local binary deployment image
##################################################
FROM ubuntu:24.04 AS omni-executor

ENV BIN_DIR=/usr/local/bin
WORKDIR $BIN_DIR

RUN apt update && apt install -y ca-certificates curl

# Copy the pre-built binary from local target directory
COPY target/release/omni-executor $BIN_DIR/omni-executor
COPY local/keystore $BIN_DIR/local/keystore

RUN chmod +x $BIN_DIR/omni-executor
RUN ls -al $BIN_DIR
RUN ldd $BIN_DIR/omni-executor && $BIN_DIR/omni-executor --version

CMD ["omni-executor"]