[package]
name = "its-validateer-fetch"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", workspace = true, features = ["chain-error"] }
derive_more = { workspace = true }

sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

itp-ocall-api = { workspace = true }
itp-types = { workspace = true }
lc-teebag-storage = { workspace = true }

[dev-dependencies]
itp-test = { workspace = true, features = ["std"] }
itc-parentchain-test = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "itp-types/std",
    "itp-ocall-api/std",
    "lc-teebag-storage/std",
]
