[package]
name = "id-itp-stf-executor"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
hex = { workspace = true, features = ["alloc"] }

sgx_tstd = { workspace = true, features = ["untrusted_time"], optional = true }
sgx_types = { workspace = true }

itp-enclave-metrics = { workspace = true }
itp-node-api = { workspace = true }
itp-ocall-api = { workspace = true }
itp-sgx-crypto = { workspace = true }
itp-sgx-externalities = { workspace = true }
itp-stf-interface = { workspace = true }
itp-stf-primitives = { workspace = true }
itp-stf-state-handler = { workspace = true }
itp-stf-state-observer = { workspace = true }
itp-time-utils = { workspace = true }
itp-types = { workspace = true }

itp-top-pool-author = { package = "id-itp-top-pool-author", path = "../top-pool-author", default-features = false }

codec = { package = "parity-scale-codec", workspace = true }
log = { workspace = true }
thiserror = { workspace = true, optional = true }
thiserror_sgx = { workspace = true, optional = true }

sp-core = { workspace = true, features = ["full_crypto"] }
sp-runtime = { workspace = true }

itc-parentchain-test = { workspace = true, optional = true }
itp-test = { workspace = true, optional = true }

[dev-dependencies]
itp-stf-state-observer = { workspace = true, features = ["std", "mocks"] }
itp-stf-interface = { workspace = true, features = ["std", "mocks"] }
itp-top-pool = { package = "id-itp-top-pool", path = "../top-pool", features = ["mocks"] }
itp-test = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
    # local
    "itp-node-api/std",
    "itp-ocall-api/std",
    "itp-sgx-crypto/std",
    "itp-sgx-externalities/std",
    "itp-stf-interface/std",
    "itp-stf-state-handler/std",
    "itp-stf-state-observer/std",
    "itp-top-pool-author/std",
    "itp-types/std",
    "itp-time-utils/std",
    # crates.io
    "log/std",
    "codec/std",
    # substrate
    "sp-core/std",
    "sp-runtime/std",
    "thiserror",
]
sgx = [
    "sgx_tstd",
    "itp-node-api/sgx",
    "itp-sgx-crypto/sgx",
    "itp-sgx-externalities/sgx",
    "itp-stf-state-handler/sgx",
    "itp-stf-state-observer/sgx",
    "itp-top-pool-author/sgx",
    "itp-time-utils/sgx",
    "thiserror_sgx",
]
test = [
    "itc-parentchain-test",
    "itp-node-api/mocks",
    "itp-test",
]
mocks = []
