[package]
name = "itc-parentchain-block-import-dispatcher"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
sgx_tstd = { workspace = true, optional = true }
sgx_types = { workspace = true }

itc-parentchain-block-importer = { path = "../block-importer", default-features = false }
itp-import-queue = { workspace = true }

thiserror = { workspace = true, optional = true }
thiserror_sgx = { workspace = true, optional = true }

log = { workspace = true }

[dev-dependencies]
itc-parentchain-block-importer = { path = "../block-importer", features = ["mocks"] }

[features]
default = ["std"]
std = [
    "itc-parentchain-block-importer/std",
    "itp-import-queue/std",
    "log/std",
    "thiserror",
]
sgx = [
    "sgx_tstd",
    "itc-parentchain-block-importer/sgx",
    "itp-import-queue/sgx",
    "thiserror_sgx",
]

# feature to export mock implementations, only to be used for dev-dependencies!
mocks = []
