[package]
name = "cross-chain-intent-executor"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
bincode = { workspace = true }
hex = { workspace = true }
parity-scale-codec = { workspace = true }
rust_decimal = { workspace = true }
solana-sdk = { workspace = true }
sp-core = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

# Local dependencies
accounting-contract-client = { workspace = true }
alloy = { workspace = true }
base58 = { workspace = true }
binance-api = { workspace = true }
ethereum-rpc = { workspace = true }
executor-core = { workspace = true }
executor-primitives = { workspace = true }
executor-storage = { workspace = true }
heima-authentication = { workspace = true }
heima-primitives = { workspace = true }
intent-asset-lock = { workspace = true }
intent-token-query = { workspace = true }
parentchain-api-interface = { workspace = true }
parentchain-rpc-client = { workspace = true }
parentchain-signer = { workspace = true }
pumpx = { workspace = true }
rand = { workspace = true }
signer-client = { workspace = true }
solana = { workspace = true }


[dev-dependencies]
accounting-contract-client = { workspace = true, features = ["mocks"] }
pumpx = { workspace = true, features = ["mocks"] }
binance-api = { workspace = true, features = ["mocks"] }
ethereum-rpc = { workspace = true, features = ["mocks"] }
signer-client = { workspace = true, features = ["mocks"] }
solana = { workspace = true, features = ["mocks"] }
tempfile = { workspace = true }
mockall = { workspace = true }
serde_json = { workspace = true }
heima-primitives = { workspace = true }
reqwest = { workspace = true }
alloy-rlp = { workspace = true }
test-log = { workspace = true }

[lints]
workspace = true
