[package]
name = "cross-chain-intent-executor"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
log = { workspace = true }

# Local dependencies
executor-core = { workspace = true }
executor-primitives = { workspace = true }
intent-asset-lock = { workspace = true }
intent-token-query = { workspace = true }
parentchain-api-interface = { workspace = true }
parentchain-rpc-client = { workspace = true }
parentchain-signer = { workspace = true }

[lints]
workspace = true
