services:
  litentry-node: # just traffic forwarding, the node network should be up already at this point
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: on-failure
    container_name: litentry-node
    networks:
      - litentry-test-network
    ports:
      # TODO: maybe not use 9912 as port
      - 9944:9912
    healthcheck:
      test: ["CMD", "nc", "-z", "litentry-node", "9912"]
      interval: 30s
      timeout: 10s
      retries: 20  bitacross-worker-1:
    image: litentry/bitacross-worker:latest
    container_name: bitacross-worker-1
    build:
      context: ${PWD}/..
      dockerfile: build.Dockerfile
      target: deployed-worker
    depends_on:
      litentry-node:
        condition: service_healthy
    devices:
      - "${SGX_PROVISION:-/dev/null}:/dev/sgx/provision"
      - "${SGX_ENCLAVE:-/dev/null}:/dev/sgx/enclave"
    volumes:
      - "${AESMD:-/dev/null}:/var/run/aesmd"
      - "${SGX_QCNL:-/dev/null}:/etc/sgx_default_qcnl.conf"
    environment:
      - RUST_LOG=info,litentry_worker=debug,ws=warn,sp_io=error,substrate_api_client=warn,itc_parentchain_light_client=info,jsonrpsee_ws_client=warn,jsonrpsee_ws_server=warn,enclave_runtime=debug,ita_stf=debug,its_rpc_handler=warn,itc_rpc_client=warn,its_consensus_common=debug,its_state=warn,its_consensus_aura=warn,aura*=warn,its_consensus_slots=warn,itp_attestation_handler=debug,http_req=debug,lc_mock_server=warn,itc_rest_client=debug,lc_credentials=debug,lc_identity_verification=debug,lc_stf_task_receiver=debug,lc_stf_task_sender=debug,lc_data_providers=debug,itp_top_pool=debug,itc_parentchain_indirect_calls_executor=debug,
    networks:
      - litentry-test-network
    healthcheck:
      test: curl -s -f http://bitacross-worker-1:4645/is_initialized || exit 1
      interval: 30s
      timeout: 10s
      retries: 20
    entrypoint:
      "/usr/local/bin/bitacross-worker --clean-reset --ws-external -M bitacross-worker-1 -T wss://bitacross-worker-1
      -u ws://litentry-node -U ws://bitacross-worker-1 -P 2011 -w 2101 -p 9912 -h 4645
      run --dev --skip-ra"
    restart: "no"
networks:
  litentry-test-network:
    driver: bridge
