services:
  worker-ping:
    image: worker-ping:${VERSION:-dev}
    devices:
      - "${SGX_PROVISION:-/dev/null}:/dev/sgx/provision"
      - "${SGX_ENCLAVE:-/dev/null}:/dev/sgx/enclave"
    volumes:
      - "${AESMD:-/dev/null}:/var/run/aesmd"
      - "${SGX_QCNL:-/dev/null}:/etc/sgx_default_qcnl.conf"
    build:
      context: .
      dockerfile: ping.Dockerfile
    depends_on: [ 'bitacross-worker-1-${VERSION}', 'bitacross-worker-2-${VERSION}' ]
    networks:
      - litentry-test-network
    entrypoint: "ping litentry-worker-2"
  pumba-network-delay:
    image: litentry-fork-producer:${VERSION:-dev}
    devices:
      - "${SGX_PROVISION:-/dev/null}:/dev/sgx/provision"
      - "${SGX_ENCLAVE:-/dev/null}:/dev/sgx/enclave"
    volumes:
      - "${AESMD:-/dev/null}:/var/run/aesmd"
      - "${SGX_QCNL:-/dev/null}:/etc/sgx_default_qcnl.conf"
    build:
      context: .
      dockerfile: fork.Dockerfile
    depends_on:
      litentry-worker-1-${VERSION}:
        condition: service_healthy
      litentry-worker-2-${VERSION}:
        condition: service_healthy
    networks:
      - litentry-test-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      "pumba --interval 3m netem --interface eth0 --duration 30s delay --time 1000 litentry-worker-2"
networks:
  litentry-test-network:
    driver: host