[package]
name = "parentchain-signer"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
parity-scale-codec = { workspace = true }
subxt-core = { workspace = true }
subxt-signer = { workspace = true }
tracing = { workspace = true }

# Local dependencies
executor-core = { workspace = true }
executor-crypto = { workspace = true }
executor-primitives = { workspace = true }
parentchain-rpc-client = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }

[lints]
workspace = true
