# Relaychain Configuration
relaychain:
  image: parity/polkadot:v0.9.9-1 # the docker image to use
  chain: rococo-local # the chain to use
  runtimeGenesisConfig: # additonal genesis override
    configuration:
      config:
        validation_upgrade_frequency: 1
        validation_upgrade_delay: 1
  env: # environment variables for all relaychain nodes
    RUST_LOG: parachain::candidate-backing=trace
  flags: # additional CLI flags for all relaychain nodes
    - --rpc-methods=unsafe
    - --no-beefy
  nodes: # nodes config
    - name: alice # the node name and session key, this imply `--alice`
      rpcPort: 9944 # default rpc port number is `9944 + global_node_index`
      port: 30333 # default libp2p port number is `30333 + global_node_index`
      flags: # additional CLI flags for this node
        - --force-authoring
      env:
        RUST_LOG: babe=debug # environment varitables for this node
    - name: bob
    - name: charlie

# Parachain Configuration
parachains:
# Config for first parachain
- image: acala/karura-node:1.3.0
  chain: # this could be a string like `dev` or a config object
    base: karura-dev # the chain to use
    collators: # override collators
      - alice # this imply //Alice
      - rXMrmePtNnyZ61hvpjfEEZ1zmKzueUnTqijDncTzE8Wa2sJ # or could be a session key public address
      - charlie
    sudo: alice # override sudo key to //Alice
  id: 2000 # override parachain id
  parachain: true # this is parachain, not parathread
  flags: # CLI flags for this parachain nodes
    - --rpc-methods=unsafe
    - --force-authoring
    - --execution=wasm
  relaychainFlags: # CLI flags for the relaychain port
    - --execution=wasm
    - --no-beefy
  env: # environment variables for this parachain nodes
    RUST_LOG: sc_basic_authorship=trace
  volumePath: /acala/data # The path to mount volume and base path, default to /data
  nodes: # nodes config
  - rpcPort: 9947
    port: 30336
    flags: # additional CLI flags for this node
      - --alice
    relaychainFlags: # additional CLI flags for relaychian part
      - --name=relaychain-alice
    env:
      RUST_LOG: aura=debug # environment varitables for this node
  - flags:
    - --bob
  - flags:
    - --charlie
