// Copyright 2020-2024 Trust Computing GmbH.
// This file is part of Litentry.
//
// Litentry is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Litentry is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Litentry.  If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_chain_bridge`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2025-03-04, STEPS: `20`, REPEAT: `50`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `parachain-dev-1`, CPU: `AMD EPYC 7B12`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("paseo-dev")`, DB CACHE: 20

// Executed Command:
// ./target/production/litentry-collator
// benchmark
// pallet
// --chain=paseo-dev
// --execution=wasm
// --db-cache=20
// --wasm-execution=compiled
// --pallet=pallet_chain_bridge
// --extrinsic=*
// --heap-pages=4096
// --steps=20
// --repeat=50
// --header=./LICENSE_HEADER
// --output=./runtime/paseo/src/weights/pallet_chain_bridge.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_chain_bridge`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_chain_bridge::WeightInfo for WeightInfo<T> {
	/// Storage: `ChainBridge::RelayerThreshold` (r:0 w:1)
	/// Proof: `ChainBridge::RelayerThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_350_000 picoseconds.
		Weight::from_parts(4_710_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ChainBridge::ChainNonces` (r:1 w:1)
	/// Proof: `ChainBridge::ChainNonces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn whitelist_chain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `175`
		//  Estimated: `3640`
		// Minimum execution time: 8_109_000 picoseconds.
		Weight::from_parts(8_531_000, 0)
			.saturating_add(Weight::from_parts(0, 3640))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ChainBridge::Relayers` (r:1 w:1)
	/// Proof: `ChainBridge::Relayers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ChainBridge::RelayerCount` (r:1 w:1)
	/// Proof: `ChainBridge::RelayerCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn add_relayer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `175`
		//  Estimated: `3640`
		// Minimum execution time: 9_420_000 picoseconds.
		Weight::from_parts(9_910_000, 0)
			.saturating_add(Weight::from_parts(0, 3640))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ChainBridge::Relayers` (r:1 w:1)
	/// Proof: `ChainBridge::Relayers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ChainBridge::RelayerCount` (r:1 w:1)
	/// Proof: `ChainBridge::RelayerCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn remove_relayer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `256`
		//  Estimated: `3721`
		// Minimum execution time: 11_090_000 picoseconds.
		Weight::from_parts(11_690_000, 0)
			.saturating_add(Weight::from_parts(0, 3721))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ChainBridge::Relayers` (r:1 w:0)
	/// Proof: `ChainBridge::Relayers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ChainBridge::ChainNonces` (r:1 w:0)
	/// Proof: `ChainBridge::ChainNonces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ChainBridge::Votes` (r:1 w:1)
	/// Proof: `ChainBridge::Votes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ChainBridge::RelayerThreshold` (r:1 w:0)
	/// Proof: `ChainBridge::RelayerThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ChainBridge::RelayerCount` (r:1 w:0)
	/// Proof: `ChainBridge::RelayerCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn acknowledge_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `318`
		//  Estimated: `3783`
		// Minimum execution time: 26_940_000 picoseconds.
		Weight::from_parts(27_670_000, 0)
			.saturating_add(Weight::from_parts(0, 3783))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ChainBridge::Relayers` (r:1 w:0)
	/// Proof: `ChainBridge::Relayers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ChainBridge::ChainNonces` (r:1 w:0)
	/// Proof: `ChainBridge::ChainNonces` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ChainBridge::Votes` (r:1 w:1)
	/// Proof: `ChainBridge::Votes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ChainBridge::RelayerThreshold` (r:1 w:0)
	/// Proof: `ChainBridge::RelayerThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ChainBridge::RelayerCount` (r:1 w:0)
	/// Proof: `ChainBridge::RelayerCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn reject_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `318`
		//  Estimated: `3783`
		// Minimum execution time: 23_240_000 picoseconds.
		Weight::from_parts(24_010_000, 0)
			.saturating_add(Weight::from_parts(0, 3783))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ChainBridge::Votes` (r:1 w:1)
	/// Proof: `ChainBridge::Votes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ChainBridge::RelayerThreshold` (r:1 w:0)
	/// Proof: `ChainBridge::RelayerThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ChainBridge::RelayerCount` (r:1 w:0)
	/// Proof: `ChainBridge::RelayerCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn eval_vote_state() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `484`
		//  Estimated: `3949`
		// Minimum execution time: 13_020_000 picoseconds.
		Weight::from_parts(13_620_000, 0)
			.saturating_add(Weight::from_parts(0, 3949))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
