// Copyright 2020-2024 Trust Computing GmbH.
// This file is part of Litentry.
//
// Litentry is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Litentry is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Litentry.  If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_identity`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2025-03-04, STEPS: `20`, REPEAT: `50`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `stress-test-server`, CPU: `AMD EPYC 7B12`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("paseo-dev")`, DB CACHE: 20

// Executed Command:
// ./litentry-collator
// benchmark
// pallet
// --chain=paseo-dev
// --execution=wasm
// --db-cache=20
// --wasm-execution=compiled
// --pallet=pallet_identity
// --extrinsic=*
// --heap-pages=4096
// --steps=20
// --repeat=50
// --header=./LICENSE_HEADER
// --output=./runtime/paseo/src/weights/pallet_identity.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_identity`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_identity::WeightInfo for WeightInfo<T> {
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn add_registrar(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 8_440_000 picoseconds.
		Weight::from_parts(9_289_308, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 2_368
			.saturating_add(Weight::from_parts(103_027, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	fn set_identity(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7015 + r * (5 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 108_580_000 picoseconds.
		Weight::from_parts(111_775_220, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 23_784
			.saturating_add(Weight::from_parts(418_310, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:100 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 100]`.
	fn set_subs_new(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `138`
		//  Estimated: `11037 + s * (2589 ±0)`
		// Minimum execution time: 10_351_000 picoseconds.
		Weight::from_parts(19_411_205, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 6_179
			.saturating_add(Weight::from_parts(3_628_426, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
			.saturating_add(Weight::from_parts(0, 2589).saturating_mul(s.into()))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:0 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[0, 100]`.
	fn set_subs_old(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `230 + p * (32 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 10_220_000 picoseconds.
		Weight::from_parts(21_100_288, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 5_326
			.saturating_add(Weight::from_parts(1_549_472, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
	}
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:0 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	/// The range of component `s` is `[0, 100]`.
	fn clear_identity(r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7107 + r * (5 ±0) + s * (32 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 59_281_000 picoseconds.
		Weight::from_parts(52_091_366, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 37_242
			.saturating_add(Weight::from_parts(680_071, 0).saturating_mul(r.into()))
			// Standard Error: 7_044
			.saturating_add(Weight::from_parts(1_495_073, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:0)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	fn request_judgement(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7005 + r * (57 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 76_550_000 picoseconds.
		Weight::from_parts(81_217_965, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 17_990
			.saturating_add(Weight::from_parts(21_579, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	fn cancel_request(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7036`
		//  Estimated: `11037`
		// Minimum execution time: 77_220_000 picoseconds.
		Weight::from_parts(79_227_346, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 8_429
			.saturating_add(Weight::from_parts(81_983, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn set_fee(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `126 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 6_270_000 picoseconds.
		Weight::from_parts(6_844_008, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 1_879
			.saturating_add(Weight::from_parts(87_017, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn set_account_id(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `126 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 6_360_000 picoseconds.
		Weight::from_parts(6_901_754, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 1_523
			.saturating_add(Weight::from_parts(83_172, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn set_fields(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `126 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 6_220_000 picoseconds.
		Weight::from_parts(6_772_192, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 1_726
			.saturating_add(Weight::from_parts(86_373, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:0)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn provide_judgement(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7083 + r * (57 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 99_510_000 picoseconds.
		Weight::from_parts(102_630_647, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 17_517
			.saturating_add(Weight::from_parts(104_082, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:0 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	/// The range of component `s` is `[0, 100]`.
	fn kill_identity(r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7367 + r * (15 ±0) + s * (32 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 76_640_000 picoseconds.
		Weight::from_parts(66_669_632, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 39_910
			.saturating_add(Weight::from_parts(839_627, 0).saturating_mul(r.into()))
			// Standard Error: 7_548
			.saturating_add(Weight::from_parts(1_480_181, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 99]`.
	fn add_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `492 + s * (36 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 26_580_000 picoseconds.
		Weight::from_parts(31_462_608, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 2_155
			.saturating_add(Weight::from_parts(85_245, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 100]`.
	fn rename_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `617 + s * (3 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 13_650_000 picoseconds.
		Weight::from_parts(16_132_867, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 986
			.saturating_add(Weight::from_parts(30_759, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 100]`.
	fn remove_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `660 + s * (35 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 30_610_000 picoseconds.
		Weight::from_parts(34_392_888, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 1_437
			.saturating_add(Weight::from_parts(66_154, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 99]`.
	fn quit_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `689 + s * (37 ±0)`
		//  Estimated: `6723`
		// Minimum execution time: 22_720_000 picoseconds.
		Weight::from_parts(25_383_757, 0)
			.saturating_add(Weight::from_parts(0, 6723))
			// Standard Error: 1_195
			.saturating_add(Weight::from_parts(58_178, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ParachainIdentity::UsernameAuthorities` (r:0 w:1)
	/// Proof: `ParachainIdentity::UsernameAuthorities` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn add_username_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_940_000 picoseconds.
		Weight::from_parts(6_411_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::UsernameAuthorities` (r:1 w:1)
	/// Proof: `ParachainIdentity::UsernameAuthorities` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn remove_username_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `3517`
		// Minimum execution time: 9_540_000 picoseconds.
		Weight::from_parts(10_080_000, 0)
			.saturating_add(Weight::from_parts(0, 3517))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::UsernameAuthorities` (r:1 w:1)
	/// Proof: `ParachainIdentity::UsernameAuthorities` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:1 w:1)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::PendingUsernames` (r:1 w:0)
	/// Proof: `ParachainIdentity::PendingUsernames` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	fn set_username_for() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `11037`
		// Minimum execution time: 70_471_000 picoseconds.
		Weight::from_parts(74_480_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `ParachainIdentity::PendingUsernames` (r:1 w:1)
	/// Proof: `ParachainIdentity::PendingUsernames` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:0 w:1)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	fn accept_username() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `11037`
		// Minimum execution time: 20_429_000 picoseconds.
		Weight::from_parts(21_629_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `ParachainIdentity::PendingUsernames` (r:1 w:1)
	/// Proof: `ParachainIdentity::PendingUsernames` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn remove_expired_approval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `3550`
		// Minimum execution time: 32_560_000 picoseconds.
		Weight::from_parts(36_550_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:1 w:0)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	fn set_primary_username() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `11037`
		// Minimum execution time: 17_110_000 picoseconds.
		Weight::from_parts(18_200_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:1 w:1)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	fn remove_dangling_username() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `135`
		//  Estimated: `11037`
		// Minimum execution time: 11_800_000 picoseconds.
		Weight::from_parts(12_480_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
