// Copyright 2020-2024 Trust Computing GmbH.
// This file is part of Litentry.
//
// Litentry is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Litentry is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Litentry.  If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_identity`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2025-03-04, STEPS: `20`, REPEAT: `50`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `stress-test-server`, CPU: `AMD EPYC 7B12`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("paseo-dev")`, DB CACHE: 20

// Executed Command:
// ./litentry-collator
// benchmark
// pallet
// --chain=paseo-dev
// --execution=wasm
// --db-cache=20
// --wasm-execution=compiled
// --pallet=pallet_identity
// --extrinsic=*
// --heap-pages=4096
// --steps=20
// --repeat=50
// --header=./LICENSE_HEADER
// --output=./runtime/paseo/src/weights/pallet_identity.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_identity`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_identity::WeightInfo for WeightInfo<T> {
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn add_registrar(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 8_450_000 picoseconds.
		Weight::from_parts(9_295_824, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 1_747
			.saturating_add(Weight::from_parts(89_112, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	fn set_identity(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7015 + r * (5 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 107_990_000 picoseconds.
		Weight::from_parts(111_083_348, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 13_782
			.saturating_add(Weight::from_parts(78_408, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:100 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 100]`.
	fn set_subs_new(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `138`
		//  Estimated: `11037 + s * (2589 ±0)`
		// Minimum execution time: 9_811_000 picoseconds.
		Weight::from_parts(20_511_595, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 6_709
			.saturating_add(Weight::from_parts(3_292_578, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
			.saturating_add(Weight::from_parts(0, 2589).saturating_mul(s.into()))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:0 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[0, 100]`.
	fn set_subs_old(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `230 + p * (32 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 9_870_000 picoseconds.
		Weight::from_parts(21_138_110, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 4_411
			.saturating_add(Weight::from_parts(1_377_138, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
	}
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:0 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	/// The range of component `s` is `[0, 100]`.
	fn clear_identity(r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7107 + r * (5 ±0) + s * (32 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 53_660_000 picoseconds.
		Weight::from_parts(54_232_117, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 18_094
			.saturating_add(Weight::from_parts(117_917, 0).saturating_mul(r.into()))
			// Standard Error: 3_422
			.saturating_add(Weight::from_parts(1_347_539, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:0)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	fn request_judgement(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7005 + r * (57 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 76_370_000 picoseconds.
		Weight::from_parts(79_369_639, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 10_430
			.saturating_add(Weight::from_parts(47_414, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	fn cancel_request(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7036`
		//  Estimated: `11037`
		// Minimum execution time: 73_780_000 picoseconds.
		Weight::from_parts(75_789_157, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 5_941
			.saturating_add(Weight::from_parts(28_790, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn set_fee(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `126 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 6_380_000 picoseconds.
		Weight::from_parts(6_915_320, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 1_395
			.saturating_add(Weight::from_parts(68_717, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn set_account_id(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `126 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 6_480_000 picoseconds.
		Weight::from_parts(6_958_958, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 1_235
			.saturating_add(Weight::from_parts(77_193, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:1)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn set_fields(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `126 + r * (57 ±0)`
		//  Estimated: `2626`
		// Minimum execution time: 6_270_000 picoseconds.
		Weight::from_parts(6_877_567, 0)
			.saturating_add(Weight::from_parts(0, 2626))
			// Standard Error: 1_323
			.saturating_add(Weight::from_parts(70_968, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::Registrars` (r:1 w:0)
	/// Proof: `ParachainIdentity::Registrars` (`max_values`: Some(1), `max_size`: Some(1141), added: 1636, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 19]`.
	fn provide_judgement(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7083 + r * (57 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 97_330_000 picoseconds.
		Weight::from_parts(99_645_371, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 10_511
			.saturating_add(Weight::from_parts(85_273, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:0 w:100)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 20]`.
	/// The range of component `s` is `[0, 100]`.
	fn kill_identity(_r: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7367 + r * (15 ±0) + s * (32 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 69_900_000 picoseconds.
		Weight::from_parts(74_816_650, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 4_406
			.saturating_add(Weight::from_parts(1_345_530, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 99]`.
	fn add_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `492 + s * (36 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 26_060_000 picoseconds.
		Weight::from_parts(30_934_667, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 1_633
			.saturating_add(Weight::from_parts(77_879, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 100]`.
	fn rename_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `617 + s * (3 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 13_700_000 picoseconds.
		Weight::from_parts(15_732_660, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 681
			.saturating_add(Weight::from_parts(27_109, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 100]`.
	fn remove_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `660 + s * (35 ±0)`
		//  Estimated: `11037`
		// Minimum execution time: 30_020_000 picoseconds.
		Weight::from_parts(33_333_663, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			// Standard Error: 1_021
			.saturating_add(Weight::from_parts(55_140, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ParachainIdentity::SuperOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SuperOf` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::SubsOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::SubsOf` (`max_values`: None, `max_size`: Some(3258), added: 5733, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 99]`.
	fn quit_sub(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `689 + s * (37 ±0)`
		//  Estimated: `6723`
		// Minimum execution time: 22_440_000 picoseconds.
		Weight::from_parts(24_629_049, 0)
			.saturating_add(Weight::from_parts(0, 6723))
			// Standard Error: 941
			.saturating_add(Weight::from_parts(54_596, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ParachainIdentity::UsernameAuthorities` (r:0 w:1)
	/// Proof: `ParachainIdentity::UsernameAuthorities` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn add_username_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_890_000 picoseconds.
		Weight::from_parts(6_220_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::UsernameAuthorities` (r:1 w:1)
	/// Proof: `ParachainIdentity::UsernameAuthorities` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn remove_username_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `3517`
		// Minimum execution time: 9_451_000 picoseconds.
		Weight::from_parts(9_920_000, 0)
			.saturating_add(Weight::from_parts(0, 3517))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::UsernameAuthorities` (r:1 w:1)
	/// Proof: `ParachainIdentity::UsernameAuthorities` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:1 w:1)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::PendingUsernames` (r:1 w:0)
	/// Proof: `ParachainIdentity::PendingUsernames` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	fn set_username_for() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `11037`
		// Minimum execution time: 72_590_000 picoseconds.
		Weight::from_parts(74_070_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `ParachainIdentity::PendingUsernames` (r:1 w:1)
	/// Proof: `ParachainIdentity::PendingUsernames` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:0 w:1)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	fn accept_username() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `11037`
		// Minimum execution time: 20_289_000 picoseconds.
		Weight::from_parts(21_160_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `ParachainIdentity::PendingUsernames` (r:1 w:1)
	/// Proof: `ParachainIdentity::PendingUsernames` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn remove_expired_approval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `3550`
		// Minimum execution time: 22_230_000 picoseconds.
		Weight::from_parts(28_351_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:1 w:0)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:1)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	fn set_primary_username() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `11037`
		// Minimum execution time: 16_980_000 picoseconds.
		Weight::from_parts(17_660_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ParachainIdentity::AccountOfUsername` (r:1 w:1)
	/// Proof: `ParachainIdentity::AccountOfUsername` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ParachainIdentity::IdentityOf` (r:1 w:0)
	/// Proof: `ParachainIdentity::IdentityOf` (`max_values`: None, `max_size`: Some(7572), added: 10047, mode: `MaxEncodedLen`)
	fn remove_dangling_username() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `135`
		//  Estimated: `11037`
		// Minimum execution time: 11_790_000 picoseconds.
		Weight::from_parts(12_220_000, 0)
			.saturating_add(Weight::from_parts(0, 11037))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
