// Copyright 2020-2024 Trust Computing GmbH.
// This file is part of Litentry.
//
// Litentry is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Litentry is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Litentry.  If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_vc_management`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2025-03-04, STEPS: `20`, REPEAT: `50`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `stress-test-server`, CPU: `AMD EPYC 7B12`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("paseo-dev")`, DB CACHE: 20

// Executed Command:
// ./heima-node
// benchmark
// pallet
// --chain=paseo-dev
// --execution=wasm
// --db-cache=20
// --wasm-execution=compiled
// --pallet=pallet_vc_management
// --extrinsic=*
// --heap-pages=4096
// --steps=20
// --repeat=50
// --header=./LICENSE_HEADER
// --output=./runtime/paseo/src/weights/pallet_vc_management.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_vc_management`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_vc_management::WeightInfo for WeightInfo<T> {
	/// Storage: `VCManagement::Delegatee` (r:0 w:1)
	/// Proof: `VCManagement::Delegatee` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn add_delegatee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_620_000 picoseconds.
		Weight::from_parts(6_190_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `VCManagement::Delegatee` (r:1 w:1)
	/// Proof: `VCManagement::Delegatee` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_delegatee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `188`
		//  Estimated: `3513`
		// Minimum execution time: 11_160_000 picoseconds.
		Weight::from_parts(12_051_000, 0)
			.saturating_add(Weight::from_parts(0, 3513))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `VCMPExtrinsicWhitelist::GroupControlOn` (r:1 w:0)
	/// Proof: `VCMPExtrinsicWhitelist::GroupControlOn` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn request_vc() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1491`
		// Minimum execution time: 6_130_000 picoseconds.
		Weight::from_parts(6_450_000, 0)
			.saturating_add(Weight::from_parts(0, 1491))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Teebag::EnclaveRegistry` (r:1 w:0)
	/// Proof: `Teebag::EnclaveRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn vc_issued() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `347`
		//  Estimated: `3812`
		// Minimum execution time: 10_049_000 picoseconds.
		Weight::from_parts(10_710_000, 0)
			.saturating_add(Weight::from_parts(0, 3812))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Teebag::EnclaveRegistry` (r:1 w:0)
	/// Proof: `Teebag::EnclaveRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn some_error() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `347`
		//  Estimated: `3812`
		// Minimum execution time: 9_760_000 picoseconds.
		Weight::from_parts(10_510_000, 0)
			.saturating_add(Weight::from_parts(0, 3812))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `VCManagement::Admin` (r:1 w:1)
	/// Proof: `VCManagement::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `136`
		//  Estimated: `1517`
		// Minimum execution time: 8_490_000 picoseconds.
		Weight::from_parts(9_010_000, 0)
			.saturating_add(Weight::from_parts(0, 1517))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `VCManagement::Admin` (r:1 w:0)
	/// Proof: `VCManagement::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `VCManagement::SchemaRegistryIndex` (r:1 w:1)
	/// Proof: `VCManagement::SchemaRegistryIndex` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VCManagement::SchemaRegistry` (r:0 w:1)
	/// Proof: `VCManagement::SchemaRegistry` (`max_values`: None, `max_size`: Some(2621), added: 5096, mode: `MaxEncodedLen`)
	fn add_schema() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `136`
		//  Estimated: `1517`
		// Minimum execution time: 11_980_000 picoseconds.
		Weight::from_parts(12_480_000, 0)
			.saturating_add(Weight::from_parts(0, 1517))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `VCManagement::Admin` (r:1 w:0)
	/// Proof: `VCManagement::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `VCManagement::SchemaRegistry` (r:1 w:1)
	/// Proof: `VCManagement::SchemaRegistry` (`max_values`: None, `max_size`: Some(2621), added: 5096, mode: `MaxEncodedLen`)
	fn disable_schema() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `254`
		//  Estimated: `6086`
		// Minimum execution time: 12_940_000 picoseconds.
		Weight::from_parts(13_740_000, 0)
			.saturating_add(Weight::from_parts(0, 6086))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `VCManagement::Admin` (r:1 w:0)
	/// Proof: `VCManagement::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `VCManagement::SchemaRegistry` (r:1 w:1)
	/// Proof: `VCManagement::SchemaRegistry` (`max_values`: None, `max_size`: Some(2621), added: 5096, mode: `MaxEncodedLen`)
	fn activate_schema() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `254`
		//  Estimated: `6086`
		// Minimum execution time: 13_030_000 picoseconds.
		Weight::from_parts(13_880_000, 0)
			.saturating_add(Weight::from_parts(0, 6086))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `VCManagement::Admin` (r:1 w:0)
	/// Proof: `VCManagement::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `VCManagement::SchemaRegistry` (r:1 w:1)
	/// Proof: `VCManagement::SchemaRegistry` (`max_values`: None, `max_size`: Some(2621), added: 5096, mode: `MaxEncodedLen`)
	fn revoke_schema() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `254`
		//  Estimated: `6086`
		// Minimum execution time: 13_710_000 picoseconds.
		Weight::from_parts(14_530_000, 0)
			.saturating_add(Weight::from_parts(0, 6086))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Teebag::EnclaveRegistry` (r:1 w:0)
	/// Proof: `Teebag::EnclaveRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn on_vc_issued() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `347`
		//  Estimated: `3812`
		// Minimum execution time: 9_780_000 picoseconds.
		Weight::from_parts(10_320_000, 0)
			.saturating_add(Weight::from_parts(0, 3812))
			.saturating_add(T::DbWeight::get().reads(1))
	}
}
