[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-credentials-v2"
version = "0.1.0"

[dependencies]
# sgx dependencies
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true, features = ["net", "thread"] }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }

# litentry
lc-common = { path = "../common", default-features = false }
lc-credentials = { path = "../credentials", default-features = false }
litentry-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
sgx = [
    "sgx_tstd",
    "litentry-primitives/sgx",
    "lc-common/sgx",
    "lc-credentials/sgx",
]
std = [
    "litentry-primitives/std",
    "lc-common/std",
    "lc-credentials/std",
]
