[package]
name = "rpc-server"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
log = { workspace = true }
jsonrpsee = { workspace = true }
tokio = { workspace = true }
rsa = { workspace = true, features = ["sha2"] }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
parity-scale-codec = { workspace = true }
hex = { workspace = true }
ring = { workspace = true }

[lints]
workspace = true
