[package]
name = "rpc-server"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
alloy = { workspace = true }
async-trait = { workspace = true }
base58 = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
email_address = { workspace = true }
ethers = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
hyperliquid_rust_sdk = { workspace = true }
jsonrpsee = { workspace = true }
parity-scale-codec = { workspace = true }
rand = { workspace = true }
rsa = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }

# Local dependencies
heima-primitives = { workspace = true }
heima-utils = { workspace = true }
oe-client-aa = { workspace = true }
oe-client-binance = { workspace = true }
oe-client-ethereum = { workspace = true }
oe-client-hyperliquid = { workspace = true }
oe-client-pumpx = { workspace = true }
oe-client-signer = { workspace = true }
oe-client-wildmeta = { workspace = true }
oe-core = { workspace = true }
oe-crypto = { workspace = true }
oe-primitives = { workspace = true }
oe-storage = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
oe-client-pumpx = { workspace = true, features = ["mocks"] }
oe-client-binance = { workspace = true, features = ["mocks"] }
oe-client-signer = { workspace = true, features = ["mocks"] }
oe-client-wildmeta = { workspace = true, features = ["mocks"] }
oe-storage = { workspace = true }
chrono = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }

[lints]
workspace = true

[features]
gramine-quote = []
test-endpoints = []
