[package]
edition = "2021"
name = "lc-mock-server"
version = "0.1.0"

[dependencies]
hex = "0.4.3"
log = "0.4"
serde_json = { version = "1.0", features = ["alloc"] }
tokio = { version = "1.5", features = ["full"] }
warp = "0.3"

# Substrate
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42" }

# Internal dependencies
ita-stf = { path = "../../../app-libs/stf" }
itp-rpc = { path = "../../../core-primitives/rpc", default-features = false }
lc-data-providers = { path = "../data-providers" }
litentry-primitives = { path = "../../primitives" }
