[package]
name = "signer-client"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
mockall = { workspace = true }
serde = { workspace = true }

# Local dependencies
executor-crypto = { workspace = true }

[lints]
workspace = true

[features]
mocks = []
