[package]
name = "ethereum-intent-executor"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
alloy = { workspace = true, features = ["contract", "signer-local", "rpc", "rpc-types", "eips"] }
async-trait = { workspace = true }
executor-core = { workspace = true }
log = { workspace = true }

# Local dependencies
executor-primitives = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
mockall = { workspace = true }
futures = { workspace = true }

[lints]
workspace = true
