[package]
name = "itp-stf-state-observer"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
itp-types = { workspace = true }
sgx_tstd = { workspace = true, optional = true }

log = { workspace = true }
thiserror = { workspace = true, optional = true }
thiserror_sgx = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
    "itp-types/std",
    "log/std",
    "thiserror",
]
sgx = [
    "sgx_tstd",
    "thiserror_sgx",
]
mocks = []
