[package]
name = "bc-itp-enclave-api"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", workspace = true }
hex = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

sgx_crypto_helper = { workspace = true }
sgx_types = { workspace = true }
sgx_urts = { workspace = true, optional = true }

frame-support = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }

itp-enclave-api-ffi = { package = "bc-itp-enclave-api-ffi", path = "ffi" }
itp-settings = { workspace = true }
itp-sgx-crypto = { workspace = true }
itp-stf-interface = { workspace = true }
itp-storage = { workspace = true }
itp-types = { workspace = true }

pallet-teebag = { workspace = true }

[features]
default = []
implement-ffi = [
    "sgx_urts",
    "itp-enclave-api-ffi/link-sgx-libs",
]
