[package]
name = "itc-rest-client"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
http = { workspace = true, optional = true }
http_req = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }

# sgx dependencies
http-sgx = { workspace = true, optional = true }
http_req-sgx = { workspace = true, optional = true }
sgx_tstd = { workspace = true, features = ["net", "thread"], optional = true }
thiserror_sgx = { workspace = true, optional = true }

base64 = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }

[features]
default = ["std"]
std = [
    "http",
    "http_req",
    "thiserror",
    "base64/std",
    "serde/std",
    "serde_json/std",
    "log/std",
    "url/std",
]
sgx = [
    "http-sgx",
    "http_req-sgx",
    "sgx_tstd",
    "thiserror_sgx",
]
