[package]
name = "pumpx"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
hex = { workspace = true }
jsonrpsee = { workspace = true, features = ["client"] }
log = { workspace = true }
parity-scale-codec = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
rsa = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
serde_with = { workspace = true }
sha2 = { workspace = true }
sp-core = { workspace = true }
url = { workspace = true }
mockall = { workspace = true }

# Local dependencies
executor-core = { workspace = true }
executor-crypto = { workspace = true }

[lints]
workspace = true

[features]
mocks = []