[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = '2021'
name = 'pallet-evm-precompile-score-staking'
version = '0.1.0'

[dependencies]
log = { workspace = true }
num_enum = { workspace = true }
parity-scale-codec = { workspace = true }

pallet-score-staking = { workspace = true }
precompile-utils = { workspace = true }

fp-evm = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-evm = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
derive_more = { workspace = true }
scale-info = { workspace = true }
serde = { workspace = true }
sha3 = { workspace = true }
precompile-utils = { workspace = true, features = ["testing"] }
pallet-timestamp = { workspace = true, features = ["std"] }
pallet-balances = { workspace = true, features = ["std", "insecure_zero_ed"] }
core-primitives = { workspace = true, features = ["std"] }
pallet-parachain-staking = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
    "log/std",
    "num_enum/std",
    "fp-evm/std",
    "pallet-evm/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-score-staking/std",
    "parity-scale-codec/std",
    "precompile-utils/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-io/std",
]
