[package]
name = "bc-signer-registry"
authors = ["Trust Computing GmbH <info@litentry.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
log = { version = "0.4", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }
thiserror = { version = "1.0.26", optional = true }


# sgx dependencies
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "master", optional = true, features = ["net", "thread"] }
thiserror-sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }


# internal dependencies
itp-settings = { path = "../../../core-primitives/settings", default-features = false }
itp-sgx-io = { path = "../../../core-primitives/sgx/io", default-features = false }
# litentry primities
litentry-primitives = { path = "../../../litentry/primitives", default-features = false }

[dev-dependencies]
base64 = { version = "0.13", features = ["alloc"] }

[features]
default = ["std"]
production = [
]
sgx = [
    "sgx_tstd",
    "thiserror-sgx",
    "itp-sgx-io/sgx",
    "litentry-primitives/sgx",
]
std = [
    "sp-std/std",
    "log/std",
    "thiserror",
    "itp-sgx-io/std",
    "litentry-primitives/std",
]
