[package]
name = "mailer"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
sendgrid = "0.23.0"
log = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }

[lints]
workspace = true
