[package]
name = "solana-intent-executor"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
oe-core = { workspace = true }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

# Local dependencies
oe-client-pumpx = { workspace = true }
oe-primitives = { workspace = true }

[lints]
workspace = true
