[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = '2021'
name = 'core-primitives'
version = '0.1.0'

[dependencies]
base58 = { workspace = true }
parity-scale-codec = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

frame-support = { workspace = true }
pallet-evm = { workspace = true }
scale-info = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

litentry-hex-utils = { workspace = true }
litentry-macros = { workspace = true }
litentry-proc-macros = { workspace = true }

[features]
default = ["std"]
std = [
    "strum/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "frame-support/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-io/std",
    "pallet-evm/std",
    "litentry-hex-utils/std",
]
development = [
    "litentry-macros/development",
]
