[package]
name = "parentchain-storage"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
log = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
rocksdb = "0.23.0"
subxt-core = { workspace = true }

executor-core = { path = "../../executor-core" }
parentchain-api-interface = { path = "../api-interface" }
parentchain-rpc-client = { path = "../rpc-client" }

[dev-dependencies]
env_logger = { workspace = true }

[lints]
workspace = true
