[package]
name = "itp-api-client-extensions"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]

# substrate
sp-consensus-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# scs
# `default-features = false` to remove the jsonrpsee dependency.
substrate-api-client = { default-features = false, features = ["std", "sync-api"], git = "https://github.com/scs/substrate-api-client.git", branch = "polkadot-v0.9.42-tag-v0.14.0" }

# local deps
itp-api-client-types = { path = "../api-client-types" }
itp-types = { path = "../../types" }

# litentry
hex = "0.4"
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

[features]
# used for unit testing only!
mocks = []
