[package]
name = "solana"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
log = { workspace = true }
mockall = { workspace = true }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-token = { workspace = true }
tokio = { workspace = true }

# Local dependencies
executor-core = { workspace = true }
pumpx = { workspace = true }

[lints]
workspace = true

[features]
mocks = []
