// Copyright 2020-2024 Trust Computing GmbH.
// This file is part of Litentry.
//
// Litentry is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Litentry is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Litentry.  If not, see <https://www.gnu.org/licenses/>.

// This file contains task related definition that will be used in
// `omni_submitNativeTask`

use executor_core::native_task::{NativeTaskTrait, NativeTaskWrapper};
use executor_crypto::{
	aes256::{aes_decrypt, Aes256Key, AesOutput},
	traits::Decrypt,
};
use parity_scale_codec::{Decode, Encode};
use std::fmt::Debug;

// RawTask is the data structure that should be passed into `omni_submitNativeTask`
// as parameters.
// It's of enum type:
// - either a plain (cleartext) NativeTaskWrapper, or
// - an opaque payload generated by aes-encrypting the NativeTaskWrapper, where the
//   aes-key itself is also encrypted by enclave's RSA shielding key
#[derive(Encode, Decode, Clone, PartialEq, Eq, Debug)]
pub enum RawTask<T: NativeTaskTrait> {
	Plain(NativeTaskWrapper<T>),
	Aes(AesTask),
}

impl<T: NativeTaskTrait> RawTask<T> {
	pub fn is_encrypted(&self) -> bool {
		matches!(self, Self::Aes(_))
	}
}

// Represent a task that can be decrypted by the enclave
pub trait DecryptableTask {
	type Error;
	fn decrypt<T: Debug>(
		&mut self,
		shielding_key: Box<dyn Decrypt<Error = T>>,
	) -> Result<Vec<u8>, Self::Error>;
}

#[derive(Encode, Decode, Default, Clone, PartialEq, Eq, Debug)]
pub struct AesTask {
	pub key: Vec<u8>,
	pub payload: AesOutput,
}

impl DecryptableTask for AesTask {
	type Error = ();

	fn decrypt<T: Debug>(
		&mut self,
		enclave_shielding_key: Box<dyn Decrypt<Error = T>>,
	) -> core::result::Result<Vec<u8>, ()> {
		let aes_key: Aes256Key = self.decrypt_aes_key(enclave_shielding_key)?;
		aes_decrypt(&aes_key, &mut self.payload).ok_or(())
	}
}

impl AesTask {
	#[allow(clippy::result_unit_err)]
	pub fn decrypt_aes_key<T: Debug>(
		&mut self,
		enclave_shielding_key: Box<dyn Decrypt<Error = T>>,
	) -> core::result::Result<Aes256Key, ()> {
		enclave_shielding_key
			.decrypt(&self.key)
			.map_err(|_| ())?
			.try_into()
			.map_err(|_| ())
	}
}
