[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-credentials"
version = "0.1.0"

[dependencies]
chrono = { workspace = true }
rust-base58 = { workspace = true, optional = true }
scale-info = { workspace = true }
thiserror = { workspace = true, optional = true }

chrono_sgx = { workspace = true, optional = true }
rand-sgx = { workspace = true, optional = true }
rust-base58-sgx = { workspace = true, optional = true }
serde_json_sgx = { workspace = true, optional = true }
sgx_tstd = { workspace = true, features = ["net", "thread"], optional = true }
thiserror_sgx = { workspace = true, optional = true }

codec = { package = "parity-scale-codec", workspace = true }
log = { workspace = true }
rand = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }

itp-stf-primitives = { workspace = true }
itp-time-utils = { workspace = true }
itp-types = { workspace = true }
sp-core = { workspace = true }

lc-common = { workspace = true }
lc-data-providers = { workspace = true }
litentry-primitives = { workspace = true }

[features]
default = ["std"]
sgx = [
    "rust-base58-sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "chrono_sgx",
    "serde_json_sgx",
    "litentry-primitives/sgx",
    "rand-sgx",
    "lc-common/sgx",
    "lc-data-providers/sgx",
]
std = [
    "rust-base58",
    "log/std",
    "serde/std",
    "serde_json/std",
    "thiserror",
    "itp-types/std",
    "litentry-primitives/std",
    "rand",
    "itp-time-utils/std",
    "lc-common/std",
    "lc-data-providers/std",
]
