version: "3.7"
services:
  relaychain-alice:
    ports:
      - ${AliceWSPort:-9946}:9944
      - ${AlicePort:-30336}:30333
    volumes:
      - relaychain-alice:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --rpc-external
      - --rpc-cors=all
      - --name=alice
      - --alice
      - --rpc-methods=unsafe
      - --execution=wasm
    environment:
      RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
    ulimits: &a1
      nofile:
        soft: 65536
        hard: 65536
  relaychain-bob:
    ports:
      - ${BobWSPort:-9947}:9944
      - ${BobPort:-30337}:30333
    volumes:
      - relaychain-bob:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --rpc-external
      - --rpc-cors=all
      - --name=bob
      - --bob
      - --rpc-methods=unsafe
      - --execution=wasm
    environment:
      RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
    ulimits: *a1
  parachain-2106-0:
    ports:
      - ${CollatorWSPort:-9944}:9944
      - ${CollatorPort:-30333}:30333
    volumes:
      - parachain-2106-0:/data
    build:
      context: .
      dockerfile: parachain-2106.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-dev-2106.json
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2106-0
      - --collator
      - --rpc-methods=unsafe
      - --force-authoring
      - --execution=wasm
      - --state-pruning=archive
      - --blocks-pruning=archive
      - --alice
      - --node-key=9e7aac1fe73c65be5c937fc95fbb9e24cd31f605696a6b4cbc34aff6a7b43968
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
    environment:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug
    ulimits: *a1
volumes:
  relaychain-alice: null
  relaychain-bob: null
  parachain-2106-0: null
