[package]
name = "parentchain-attestation"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
hex = { workspace = true }
parity-scale-codec = { workspace = true }
subxt-core = { workspace = true }
subxt-signer = { workspace = true }
tracing = { workspace = true }

# Local dependencies
executor-primitives = { workspace = true }
parentchain-api-interface = { workspace = true }
parentchain-rpc-client = { workspace = true }
parentchain-signer = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }

[lints]
workspace = true

[features]
gramine-quote = []
