[package]
name = "executor-primitives"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
base58 = { workspace = true }
base64 = { workspace = true }
bitcoin = { workspace = true, features = ["secp-recovery"] }
hex = { workspace = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tracing = { workspace = true }

executor-crypto = { workspace = true }
heima-primitives = { workspace = true }
heima-utils = { workspace = true }
sp-core = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
