[package]
name = "bc-musig2-event"
authors = ["Trust Computing GmbH <info@litentry.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
threadpool = { workspace = true, optional = true }

# sgx dependencies
sgx_tstd = { workspace = true, features = ["net", "thread"], optional = true }
threadpool_sgx = { workspace = true, optional = true }

bc-enclave-registry = { path = "../bc-enclave-registry", default-features = false }
bc-musig2-ceremony = { path = "../bc-musig2-ceremony", default-features = false }
itc-direct-rpc-client = { workspace = true }
itc-direct-rpc-server = { workspace = true }
itp-ocall-api = { workspace = true }
itp-rpc = { workspace = true }
itp-sgx-crypto = { workspace = true }
itp-types = { workspace = true }
itp-utils = { workspace = true }
lc-direct-call = { path = "../../../litentry/core/direct-call", default-features = false }
litentry-primitives = { workspace = true }
rand = { version = "0.8.5", optional = true }
sgx_rand = { workspace = true, optional = true }
sp-core = { workspace = true, features = ["full_crypto"] }

codec = { workspace = true }
log = { workspace = true }

[dev-dependencies]
rand = { version = "0.8.5" }

[features]
default = ["std"]
std = [
    "itc-direct-rpc-client/std",
    "itc-direct-rpc-server/std",
    "log/std",
    "itp-types/std",
    "litentry-primitives/std",
    "itp-rpc/std",
    "bc-musig2-ceremony/std",
    "bc-enclave-registry/std",
    "lc-direct-call/std",
    "itp-sgx-crypto/std",
    "rand",
    "threadpool",
]
sgx = [
    "sgx_tstd",
    "itc-direct-rpc-client/sgx",
    "itc-direct-rpc-server/sgx",
    "litentry-primitives/sgx",
    "itp-rpc/sgx",
    "bc-musig2-ceremony/sgx",
    "bc-enclave-registry/sgx",
    "lc-direct-call/sgx",
    "itp-sgx-crypto/sgx",
    "sgx_rand",
    "threadpool_sgx",
]
