[package]
name = "executor-storage"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
rocksdb = "0.23.0"
tracing = { workspace = true }

# Local dependencies
executor-crypto = { workspace = true }
executor-primitives = { workspace = true }
sp-core = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }

[lints]
workspace = true
