[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-credentials"
version = "0.1.0"

[dependencies]
# std dependencies
chrono = { version = "0.4.19", default-features = false, features = ["alloc"] }
rust-base58 = { package = "rust-base58", version = "0.0.4", optional = true }
scale-info = { version = "2.4.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.38", optional = true }

# sgx dependencies
chrono_sgx = { package = "chrono", git = "https://github.com/mesalock-linux/chrono-sgx", optional = true }
rand-sgx = { package = "rand", git = "https://github.com/mesalock-linux/rand-sgx", tag = "sgx_1.1.3", features = ["sgx_tstd"], optional = true }
rust-base58-sgx = { git = "https://github.com/mesalock-linux/rust-base58-sgx", optional = true, package = "rust-base58", features = ["mesalock_sgx"] }
serde_json_sgx = { package = "serde_json", tag = "sgx_1.1.3", git = "https://github.com/mesalock-linux/serde-json-sgx", optional = true }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true, features = ["net", "thread"] }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
hex = { version = "0.4.3", default-features = false }
log = { version = "0.4", default-features = false }
rand = { version = "0.7", optional = true }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

# internal dependencies
itp-stf-primitives = { default-features = false, path = "../../../core-primitives/stf-primitives" }
itp-time-utils = { path = "../../../core-primitives/time-utils", default-features = false }
itp-types = { path = "../../../core-primitives/types", default-features = false }
itp-utils = { path = "../../../core-primitives/utils", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42", default-features = false }

# litentry
lc-common = { path = "../common", default-features = false }
lc-data-providers = { path = "../data-providers", default-features = false }
litentry-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
sgx = [
    "rust-base58-sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "chrono_sgx",
    "serde_json_sgx",
    "litentry-primitives/sgx",
    "rand-sgx",
    "itp-time-utils/sgx",
    "lc-common/sgx",
    "lc-data-providers/sgx",
]
std = [
    "rust-base58",
    "log/std",
    "serde/std",
    "serde_json/std",
    "thiserror",
    "itp-types/std",
    "itp-utils/std",
    "litentry-primitives/std",
    "rand",
    "itp-time-utils/std",
    "lc-common/std",
    "lc-data-providers/std",
]
