[package]
name = "bc-enclave-registry"
authors = ["Trust Computing GmbH <info@litentry.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { workspace = true }
log = { workspace = true }
sp-std = { workspace = true }

sgx_tstd = { workspace = true, optional = true, features = ["net", "thread"] }

thiserror_sgx = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }

itp-settings = { workspace = true }
itp-sgx-io = { workspace = true }
litentry-primitives = { workspace = true }

[dev-dependencies]
base64 = { workspace = true, features = ["alloc"] }

[features]
default = ["std"]
production = [
]
sgx = [
    "sgx_tstd",
    "thiserror_sgx",
    "itp-sgx-io/sgx",
    "litentry-primitives/sgx",
]
std = [
    "sp-std/std",
    "log/std",
    "thiserror",
    "itp-sgx-io/std",
    "litentry-primitives/std",
]
