#!/bin/bash

# Script to update demo app addresses after running deploy-local.sh
# This extracts the deployed contract addresses and creates/updates the .env.local file

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEMO_APP_DIR="$SCRIPT_DIR/aa-demo-app"
ENV_FILE="$DEMO_APP_DIR/.env.local"

echo "🔍 Extracting deployed contract addresses..."

# Function to extract address from forge output or broadcast file
extract_addresses() {
    local broadcast_file="$SCRIPT_DIR/broadcast/DeployLocal.s.sol/1337/run-latest.json"
    
    # Check for old broadcast file first
    local old_broadcast_file="$SCRIPT_DIR/broadcast/DeployAA.s.sol/1337/run-latest.json"
    if [ -f "$old_broadcast_file" ] && [ ! -f "$broadcast_file" ]; then
        broadcast_file="$old_broadcast_file"
        echo "⚠️  Using old broadcast file format. Consider re-running deploy-local.sh"
    fi
    
    if [ ! -f "$broadcast_file" ]; then
        echo "❌ Broadcast file not found. Please run deploy-local.sh first."
        exit 1
    fi
    
    # Extract addresses using grep and sed
    ENTRYPOINT_ADDRESS=$(grep -A2 '"contractName": "EntryPoint"' "$broadcast_file" | grep '"contractAddress"' | sed 's/.*"contractAddress": "\(.*\)".*/\1/' | head -1)
    # Try both SmartAccountFactory (old) and OmniAccountFactory (new) names
    FACTORY_ADDRESS=$(grep -A2 '"contractName": "OmniAccountFactory"' "$broadcast_file" | grep '"contractAddress"' | sed 's/.*"contractAddress": "\(.*\)".*/\1/' | head -1)
    if [ -z "$FACTORY_ADDRESS" ]; then
        FACTORY_ADDRESS=$(grep -A2 '"contractName": "SmartAccountFactory"' "$broadcast_file" | grep '"contractAddress"' | sed 's/.*"contractAddress": "\(.*\)".*/\1/' | head -1)
    fi
    
    # OmniAccount implementation is created by the factory, need to find it differently
    # For now, we'll leave it empty as it's deployed by the factory
    OMNI_ACCOUNT_IMPL_ADDRESS=""
    
    echo "Found addresses:"
    echo "  EntryPoint: $ENTRYPOINT_ADDRESS"
    echo "  OmniAccountFactory: $FACTORY_ADDRESS"
}

# Function to create or update .env.local
update_env_file() {
    echo "📝 Updating $ENV_FILE..."
    
    # Create backup if file exists
    if [ -f "$ENV_FILE" ]; then
        cp "$ENV_FILE" "$ENV_FILE.backup"
        echo "  Created backup: $ENV_FILE.backup"
    fi
    
    # Create new env file
    cat > "$ENV_FILE" << EOF
# Auto-generated by update-demo-addresses.sh
# Last updated: $(date)

# Chain Configuration (Anvil local)
NEXT_PUBLIC_CHAIN_ID=1337

# Contract Addresses
NEXT_PUBLIC_ENTRYPOINT_ADDRESS=$ENTRYPOINT_ADDRESS
NEXT_PUBLIC_FACTORY_ADDRESS=$FACTORY_ADDRESS
NEXT_PUBLIC_OMNI_ACCOUNT_IMPL_ADDRESS=$OMNI_ACCOUNT_IMPL_ADDRESS

# Local RPC URL
NEXT_PUBLIC_RPC_URL=http://localhost:8545

# Add your WalletConnect Project ID here
# NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=your_project_id_here
EOF

    echo "✅ Updated $ENV_FILE with deployed addresses"
}

# Function to show next steps
show_next_steps() {
    echo ""
    echo "🎉 Demo app configuration updated!"
    echo ""
    echo "Next steps:"
    echo "1. cd aa-demo-app"
    echo "2. npm install (if not already done)"
    echo "3. npm run dev"
    echo "4. Open http://localhost:3000"
    echo ""
    echo "Contract addresses:"
    echo "  EntryPoint: $ENTRYPOINT_ADDRESS"
    echo "  Factory: $FACTORY_ADDRESS"
    echo ""
    echo "Make sure Anvil is running on port 8545 (started by deploy-local.sh)"
}

# Main execution
extract_addresses
update_env_file
show_next_steps