[package]
name = "itp-enclave-metrics"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
sgx_tstd = { workspace = true, optional = true }
codec = { workspace = true, features = ["full"] }
litentry-primitives = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "litentry-primitives/std",
]
sgx = [
    "sgx_tstd",
    "litentry-primitives/sgx",
]
