[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "polkadot"
default_args = ["--no-hardware-benchmarks", "-l=parachain=debug"]
chain = "rococo-local"

[relaychain.genesis.runtimeGenesis.patch.configuration.config.scheduler_params]
lookahead = 2

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = {{PARA_ID}}
chain = "{{PARA_CHAIN_SPEC}}"
cumulus_based = true

[[parachains.collators]]
name = "collator1"
command = "litentry-collator"
args = ["--no-hardware-benchmarks", "--force-authoring", "--enable-evm-rpc"]
ws_port = {{COLLATOR_WS_PORT}}
