[package]
name = "itp-sgx-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = { workspace = true }
codec = { workspace = true }
derive_more = { workspace = true }
log = { workspace = true }
ofb = { workspace = true }
serde_json = { workspace = true, optional = true }

# sgx deps
serde_json-sgx = { workspace = true, optional = true }
sgx_crypto_helper = { workspace = true }
sgx_rand = { workspace = true, optional = true }
sgx_tstd = { workspace = true, optional = true }
sgx_types = { workspace = true }

# substrate 
sp-core = { workspace = true }

# local deps
itp-sgx-io = { workspace = true }
itp-sgx-temp-dir = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "log/std",
    "itp-sgx-io/std",
    "sp-core/std",
    "serde_json/std",
    "sgx_crypto_helper/default",
]
sgx = [
    "sgx_crypto_helper/mesalock_sgx",
    "sgx_tstd",
    "sgx_rand",
    "itp-sgx-io/sgx",
    "serde_json-sgx",
]
mocks = []
test = [
    # features
    "mocks",
    "sgx",
    # deps
    "itp-sgx-temp-dir",
]
