[package]
name = "itp-enclave-metrics"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sgx
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# no-std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full"] }
lc-stf-task-sender = { path = "../../litentry/core/stf-task/sender", default-features = false }
litentry-primitives = { path = "../../litentry/primitives", default-features = false }
substrate-fixed = { default-features = false, git = "https://github.com/encointer/substrate-fixed", tag = "v0.5.9" }

[features]
default = ["std"]
std = [
    "substrate-fixed/std",
    "codec/std",
    "litentry-primitives/std",
    "lc-stf-task-sender/std",

]
sgx = [
    "sgx_tstd",
    "litentry-primitives/sgx",
    "lc-stf-task-sender/sgx",
]
