[package]
name = "itc-parentchain-indirect-calls-executor"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
sgx_tstd = { workspace = true, optional = true }
sgx_types = { workspace = true }

itp-api-client-types = { workspace = true }
itp-enclave-metrics = { workspace = true }
itp-node-api = { workspace = true }
itp-ocall-api = { workspace = true }
itp-sgx-crypto = { workspace = true }
itp-stf-executor = { workspace = true }
itp-stf-primitives = { workspace = true }
itp-test = { workspace = true }
itp-top-pool-author = { workspace = true }
itp-types = { workspace = true }

futures_sgx = { workspace = true, optional = true }
thiserror_sgx = { workspace = true, optional = true }

futures = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }

codec = { workspace = true }
log = { workspace = true }

binary-merkle-tree = { workspace = true }
sp-core = { workspace = true, features = ["full_crypto"] }
sp-runtime = { workspace = true }

litentry-primitives = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
itp-node-api = { workspace = true, features = ["std", "mocks"] }
itp-sgx-crypto = { workspace = true, features = ["std", "mocks"] }
itp-stf-executor = { workspace = true, features = ["std", "mocks"] }
itp-test = { workspace = true, features = ["std"] }
itp-top-pool-author = { workspace = true, features = ["std", "mocks"] }
itc-parentchain-test = { workspace = true, features = ["std"] }
ita-parentchain-interface = { workspace = true, features = ["std"] }
lc-evm-dynamic-assertions = { pworkspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
    "codec/std",
    "futures",
    "itp-node-api/std",
    "itp-sgx-crypto/std",
    "itp-stf-executor/std",
    "itp-top-pool-author/std",
    "itp-api-client-types/std",
    "itp-test/std",
    "itp-types/std",
    "itp-enclave-metrics/std",
    "log/std",
    #substrate
    "binary-merkle-tree/std",
    "sp-core/std",
    "sp-runtime/std",
    "thiserror",
    # litentry
    "litentry-primitives/std",
]
sgx = [
    "sgx_tstd",
    "futures_sgx",
    "itp-node-api/sgx",
    "itp-sgx-crypto/sgx",
    "itp-stf-executor/sgx",
    "itp-top-pool-author/sgx",
    "itp-enclave-metrics/sgx",
    "itp-test/sgx",
    "thiserror_sgx",
    # litentry
    "litentry-primitives/sgx",
]
