[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-service"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sgx dependencies
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true, features = ["net", "thread"] }

# no_std dependencies
log = { version = "0.4", default-features = false }

# litentry
lc-common = { path = "../common", default-features = false }
lc-data-providers = { path = "../data-providers", default-features = false }
litentry-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
sgx = [
    "sgx_tstd",
    "litentry-primitives/sgx",
    "lc-common/sgx",
    "lc-data-providers/sgx",
]
std = [
    "log/std",
    "litentry-primitives/std",
    "lc-common/std",
    "lc-data-providers/std",
]
