[package]
name = "executor-crypto"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
ethers = { workspace = true }
jsonwebtoken = { workspace = true }
parity-scale-codec = { workspace = true }
rand = { workspace = true }
ring = { workspace = true }
rsa = { workspace = true, features = ["sha2"] }
secp256k1 = { workspace = true, features = ["std", "global-context", "recovery"] }
serde = { workspace = true }
serde_with = { workspace = true }
sp-core = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
chrono = { workspace = true }

[lints]
workspace = true
