[package]
name = "executor-worker"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
env_logger = { workspace = true }
executor-core = { path = "../executor-core" }
hex = "0.4.3"
intention-executor = { path = "../ethereum/intention-executor" }
log = { workspace = true }
parentchain-listener = { path = "../parentchain/listener" }
scale-encode = { workspace = true }
serde_json = "1.0.127"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
