[package]
name = "executor-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {  workspace = true, features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.127"
scale-encode = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
intention-executor = { path = "../ethereum/intention-executor" }
executor-core = { path = "../executor-core" }
parentchain-listener = { path = "../parentchain/listener" }
hex = "0.4.3"