[package]
name = "executor-worker"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
alloy = { workspace = true, features = ["signer-local"] }
clap = { workspace = true, features = ["derive"] }
ethers = { workspace = true }
hex = { workspace = true }
jsonrpsee = { workspace = true, features = ["ws-client"] }
metrics-exporter-prometheus = { workspace = true }
rand = { workspace = true }
rsa = { workspace = true }
rust_decimal = { workspace = true }
scale-encode = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }

# Local dependencies
aa-contracts-client = { workspace = true }
accounting-contract-client = { workspace = true }
binance-api = { workspace = true }
config-loader = { workspace = true }
cross-chain-intent-executor = { workspace = true }
ethereum-intent-executor = { workspace = true }
ethereum-rpc = { workspace = true }
executor-core = { workspace = true }
executor-crypto = { workspace = true }
executor-primitives = { workspace = true }
executor-storage = { workspace = true }
heima-identity-verification = { workspace = true }
intent-asset-lock = { workspace = true }
mock-server = { workspace = true }
native-task-handler = { workspace = true }
pumpx = { workspace = true }
rpc-server = { workspace = true }
signer-client = { workspace = true }
solana = { workspace = true }
solana-intent-executor = { workspace = true }
wildmeta-api = { workspace = true }

[features]
default = []
mock-server = []
test-endpoints = ["rpc-server/test-endpoints"]

[lints]
workspace = true
