[package]
name = "lc-parachain-extrinsic-task-receiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", default-features = false }

# sgx dependencies
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "master", features = ["net", "thread"], optional = true }

# substrate dependencies
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42", default-features = false }

# internal dependencies
itp-extrinsics-factory = { path = "../../../../core-primitives/extrinsics-factory", default-features = false }
itp-ocall-api = { path = "../../../../core-primitives/ocall-api", default-features = false }
itp-types = { path = "../../../../core-primitives/types", default-features = false }
lc-parachain-extrinsic-task-sender = { path = "../sender", default-features = false }

[features]
default = ["std"]
std = [
    "log/std",
    "lc-parachain-extrinsic-task-sender/std",
]
sgx = [
    "sgx_tstd",
    "lc-parachain-extrinsic-task-sender/sgx",
]
