name: Build docker with args

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The commit SHA or tag for checking out code
        default: ""
        required: false
      cargo_profile:
        type: choice
        description: which profile to use in cargo
        options:
          - release
          - production
      docker_tag:
        description: The tag for the built docker image
        required: true
      args:
        description: Args to pass to `cargo build`, e.g. --features=runtime-benchmarks
        default: ""
        required: false

env:
  DOCKER_BUILDKIT: 1

jobs:
  ## build docker image of client binary with args ##
  build-docker-with-args:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes on ${{ github.event.inputs.ref || github.ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
          fetch-depth: 0

      - name: Dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push docker image
        run: |
          docker pull litentry/litentry-parachain:${{ github.event.inputs.docker_tag }}
          docker tag litentry/litentry-parachain:${{ github.event.inputs.docker_tag }} litentry/litentry-parachain:latest

      - name: Enable corepack and pnpm
        run: corepack enable && corepack enable pnpm

      - name: test-ts
        timeout-minutes: 40
        run: |
          make test-ts-litentry
