name: 'Release bot'
on:
  release:
    types: [released]

jobs:
  release-bot:
    runs-on: ubuntu-22.04
    # this means the release contains a new docker image (thus a new client)
    if: contains(github.event.release.body, 'litentry/litentry-parachain:v')
    steps:
      - name: Post discord message
        env:
          DISCORD_WEBHOOK: ${{ secrets.RELEASE_BOT_DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        continue-on-error: true
        with:
          args: |
            Hi @everyone,
            🚀 A new client release has been built: https://github.com/litentry/litentry-parachain/releases/tag/${{ github.event.release.tag_name }}
            ✨ Please update the client using the docker image litentry/litentry-parachain:${{ github.event.release.tag_name }}


