name: Simulate runtime upgrade

on:
  release:
    types: [released]

  workflow_dispatch:
    inputs:
      release_tag:
        description: runtime.wasm release_tag
        required: true

env:
  SUBWASM_VERSION: 0.19.1
  RELEASE_TAG: ${{ github.event.inputs.release_tag || github.event.release.tag_name }}

jobs:
  simulate-runtime-upgrade:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        chain:
          - litmus
          - litentry
          - rococo
    steps:
      - name: Checkout codes on ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable corepack and pnpm
        run: corepack enable && corepack enable pnpm

      - name: Fork ${{ matrix.chain }} and launch parachain
        timeout-minutes: 20
        run: |
          ./scripts/fork-parachain-and-launch.sh ${{ matrix.chain }}

      - name: Install subwasm ${{ env.SUBWASM_VERSION }}
        run: |
          wget https://github.com/chevdor/subwasm/releases/download/v${{ env.SUBWASM_VERSION }}/subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
          sudo dpkg -i subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
          subwasm --version

      - name: Test runtime upgrade
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 10
        run: |
          ./scripts/runtime-upgrade.sh ${{ matrix.chain }}-parachain-runtime.compact.compressed.wasm ${{ env.RELEASE_TAG }}

      - name: Collect docker logs if test fails
        continue-on-error: true
        uses: jwalton/gh-docker-logs@v2
        if: failure()
        with:
          tail: all
          dest: docker-logs

      - name: Upload docker logs if test fails
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.chain }}-docker-logs
          path: docker-logs
          if-no-files-found: ignore
          retention-days: 3
