services:
  demo-shielding-unshielding-multiworker:
    image: litentry/identity-cli:latest
    devices:
      - "${SGX_PROVISION:-/dev/null}:/dev/sgx/provision"
      - "${SGX_ENCLAVE:-/dev/null}:/dev/sgx/enclave"
    volumes:
      - "${AESMD:-/dev/null}:/var/run/aesmd"
      - "${SGX_QCNL:-/dev/null}:/etc/sgx_default_qcnl.conf"
    build:
      context: ${PWD}/..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on:
      litentry-node:
        condition: service_healthy
      litentry-worker-1:
        condition: service_healthy
    environment:
      - RUST_LOG=warn,ws=warn,itc_rpc_client=debug,litentry_cli=debug
    networks:
      - litentry-test-network
    entrypoint:
      "/usr/local/worker-cli/demo_shielding_unshielding.sh -t first -p 9912 -u ws://litentry-node
      -V wss://litentry-worker-1 -P 2011 -C /usr/local/bin/litentry-cli 2>&1"
    restart: "no"
networks:
  litentry-test-network:
    driver: bridge