services:
    lit-ts-api-package-build:
        image: litentry/identity-cli:latest
        container_name: litentry-lit-ts-api-package-build
        volumes:
            - ../client-api:/client-api
            - ../cli:/usr/local/worker-cli
        build:
            context: ..
            dockerfile: build.Dockerfile
            target: deployed-client
        depends_on:
            litentry-node:
                condition: service_healthy
            litentry-worker-1:
                # using +service_started+ over +service_healthy+ since worker runs successfully but can not connect to parachain
                # as requires additional pre-setup for parachain image which built in production mode
                # for generating types there is no need for fully workable interaction between worker and parachain
                condition: service_started
        networks:
            - litentry-test-network
        entrypoint: 
            "/usr/local/worker-cli/lit_ts_api_package_build.sh -p 9912 -u ws://litentry-node -W http://litentry-node -V ws://litentry-worker-1 -A 2011 -C /usr/local/bin/litentry-cli 2>&1"
        restart: "no"
networks:
    litentry-test-network:
        driver: bridge
