services:
    lit-assertion-contracts-test:
        image: litentry/identity-cli:latest
        container_name: lit-assertion-contracts-test
        volumes:
            - ../ts-tests:/ts-tests
            - ../client-api:/client-api
            - ../cli:/usr/local/worker-cli
            - ../litentry/core/assertion-build/src/dynamic:/assertion-contracts

        build:
            context: ..
            dockerfile: build.Dockerfile
            target: deployed-client
        depends_on:
            litentry-worker-1:
                condition: service_healthy
        network_mode: host
        entrypoint: "bash -c '/usr/local/worker-cli/lit_ts_integration_test.sh assertion_contracts.test.ts 2>&1' "
        restart: "no"
