services:
    lit-resume-worker:
        image: litentry/identity-worker:latest
        container_name: litentry-worker
        volumes:
            - ../ts-tests:/ts-tests
            - ../client-api:/client-api
            - ../cli:/usr/local/worker-cli
        build:
            context: ..
            dockerfile: build.Dockerfile
            target: deployed-worker
        network_mode: host
        entrypoint: "bash -c '/usr/local/worker-cli/lit_ts_worker_test.sh resuming_worker.test.ts 2>&1' "
        restart: "no"
