services:
  lit-parentchain-nonce:
    image: litentry/identity-cli:latest
    container_name: litentry-parentchain-nonce
    volumes:
      - ../cli:/usr/local/worker-cli
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-client
    network_mode: host
    depends_on:
      litentry-worker-1:
        condition: service_healthy
    entrypoint:
      "/usr/local/worker-cli/lit_parentchain_nonce.sh -p 9944
      -V ws://litentry-worker-1 -A 2011 -C /usr/local/bin/litentry-cli 2>&1"
    restart: "no"