[package]
name = "bc-task-sender"
authors = ["Trust Computing GmbH <info@litentry.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { workspace = true, optional = true }

futures_sgx = { workspace = true, optional = true }
sgx_tstd = { workspace = true, features = ["net", "thread"], optional = true }

codec = { workspace = true }
lazy_static = { workspace = true }

litentry-primitives = { workspace = true }

[features]
default = ["std"]
sgx = [
    "futures_sgx",
    "sgx_tstd",
    "futures_sgx",
    "litentry-primitives/sgx",
]
std = [
    "futures",
    "futures",
    "litentry-primitives/std",
]
