[package]
name = "intent-asset-lock"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition.workspace = true

[dependencies]
parity-scale-codec = { workspace = true }
ruint = { workspace = true, features = ["parity-scale-codec"] }
tracing = { workspace = true }

# Local dependencies
executor-core = { workspace = true }
executor-primitives = { workspace = true }
executor-storage = { workspace = true }
heima-primitives = { workspace = true }


[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
